# Generated by Django 3.2.7 on 2021-11-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bag_id", models.CharField(max_length=255, unique=True)),
                (
                    "street_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number", models.IntegerField(blank=True, null=True)),
                (
                    "suffix_letter",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("suffix", models.CharField(blank=True, max_length=4, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=7, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
