# Generated by Django 3.1.2 on 2020-10-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
          BEGIN;
          SELECT setval(pg_get_serial_sequence('"addresses_address"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "addresses_address";
          COMMIT;
        """
        )
    ]
