# Generated by Django 3.2.7 on 2021-11-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        # TrigramExtension(),
    ]
