# Generated by Django 3.2.7 on 2022-03-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_auto_20211127_1739"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousingCorporation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("bwv_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="housing_corporation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="addresses.housingcorporation",
            ),
        ),
    ]
