# Generated by Django 5.2.14 on 2026-08-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0006_auto_20221117_1259"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
    ]
