# Generated by Django 5.2.12 on 2026-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0006_auto_20221117_1259"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AddField(
            model_name="address",
            name="wijk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
