# Generated by Django 3.1.2 on 2020-10-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="values",
            field=models.JSONField(default=dict),
        ),
    ]
