# Generated by Django 3.2.13 on 2024-02-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_default_column_ids_azure"),
    ]

    operations = []
