# Generated by Django 3.1.2 on 2020-10-29 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_delete_address"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("events", "0002_auto_20201029_0527"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="case",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="cases.case"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="emitter_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="contenttypes.contenttype",
            ),
        ),
    ]
