# Generated by Django 3.1.2 on 2020-10-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20201029_0702"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="emitter_type",
            new_name="content_type",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="emitter_id",
            new_name="object_id",
        ),
    ]
