# Generated by Django 3.1.2 on 2020-10-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_delete_address"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("events", "0004_auto_20201029_0708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="cases.case",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
