# Generated by Django 3.1.2 on 2020-10-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_auto_20201029_0714"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="values",
        ),
    ]
