# Generated by Django 3.1.2 on 2020-10-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_auto_20201029_0938"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="object_id",
            new_name="emitter_id",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="content_type",
            new_name="emitter_type",
        ),
    ]
