# Generated by Django 3.1.2 on 2020-11-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_auto_20201102_0905"),
        ("events", "0009_auto_20201102_0905"),
    ]

    operations = []
