# Generated by Django 3.1.2 on 2020-11-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_auto_20201030_0437"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("events", "0011_merge_20201103_0239"),
    ]

    operations = [migrations.RenameModel("Event", "CaseEvent")]
