# Generated by Django 3.1.2 on 2020-11-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_auto_20201103_0403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEBRIEFING", "DEBRIEFING"),
                    ("VISIT", "VISIT"),
                    ("CASE", "CASE"),
                ],
                max_length=250,
            ),
        ),
    ]
