# Generated by Django 3.1.5 on 2021-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_auto_20201106_0416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEBRIEFING", "DEBRIEFING"),
                    ("VISIT", "VISIT"),
                    ("CASE", "CASE"),
                    ("SUMMON", "SUMMON"),
                ],
                max_length=250,
            ),
        ),
    ]
