# Generated by Django 3.1.5 on 2021-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_auto_20210204_1433"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEBRIEFING", "DEBRIEFING"),
                    ("VISIT", "VISIT"),
                    ("CASE", "CASE"),
                    ("SUMMON", "SUMMON"),
                    ("GENERIC_TASK", "GENERIC_TASK"),
                ],
                max_length=250,
            ),
        ),
    ]
