# Generated by Django 3.1.7 on 2021-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_auto_20210210_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEBRIEFING", "DEBRIEFING"),
                    ("VISIT", "VISIT"),
                    ("CASE", "CASE"),
                    ("SUMMON", "SUMMON"),
                    ("GENERIC_TASK", "GENERIC_TASK"),
                    ("SCHEDULE", "SCHEDULE"),
                ],
                max_length=250,
            ),
        ),
    ]
