# Generated by Django 3.1.8 on 2021-05-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_auto_20210331_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEBRIEFING", "DEBRIEFING"),
                    ("VISIT", "VISIT"),
                    ("CASE", "CASE"),
                    ("SUMMON", "SUMMON"),
                    ("GENERIC_TASK", "GENERIC_TASK"),
                    ("SCHEDULE", "SCHEDULE"),
                    ("CITIZEN_REPORT", "CITIZEN_REPORT"),
                ],
                max_length=250,
            ),
        ),
    ]
