# Generated by Django 3.1.7 on 2021-06-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_auto_20210517_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEBRIEFING", "DEBRIEFING"),
                    ("VISIT", "VISIT"),
                    ("CASE", "CASE"),
                    ("CASE_CLOSE", "CASE_CLOSE"),
                    ("SUMMON", "SUMMON"),
                    ("GENERIC_TASK", "GENERIC_TASK"),
                    ("SCHEDULE", "SCHEDULE"),
                    ("CITIZEN_REPORT", "CITIZEN_REPORT"),
                ],
                max_length=250,
            ),
        ),
    ]
