# Generated by Django 3.1.7 on 2021-05-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_auto_20210517_1702"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskModelEventEmitter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camunda_task_id",
                    models.CharField(
                        blank=True, default="-1", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
