# Generated by Django 3.2.5 on 2021-08-19 13:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_group_display_name"),
        ("users", "0002_auto_20201014_0557"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
