# Generated by Django 3.2.5 on 2021-08-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usergroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("create_case", "Create a new Case"),
                    ("close_case", "Close a Case (by performing the last task)"),
                    ("perform_task", "Can perform a tasks"),
                    (
                        "access_personal_data_register",
                        "Can access 'BRP' (persoonsgegevens / ingeschreven personen)",
                    ),
                    (
                        "access_business_register",
                        "Can access 'Handelsregister' (bedrijfseigenaren van panden, bedrijfsinformatie)",
                    ),
                    ("access_signals", "Can access 'SIA' (signalen)"),
                    ("access_recovery_check", "Can access 'invorderingscheck'"),
                    (
                        "access_sensitive_dossiers",
                        "Can read gevoelige dossiers",
                    ),
                    ("access_sigital_surveillance", "Can read 'Digitaal toezicht'"),
                    (
                        "access_document_management_system",
                        "Can access 'DMS' (Alfresco / Decos)",
                    ),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
