# Generated by Django 3.2.7 on 2021-12-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("create_case", "Create a new Case"),
                    ("close_case", "Close a Case (by performing the last task)"),
                    ("perform_task", "Can perform a tasks"),
                    (
                        "access_personal_data_register",
                        "Can access 'BRP' (persoonsgegevens / ingeschreven personen)",
                    ),
                    (
                        "access_business_register",
                        "Can access 'Handelsregister' (bedrijfseigenaren van panden, bedrijfsinformatie)",
                    ),
                    ("access_signals", "Can access 'SIA' (signalen)"),
                    ("access_recovery_check", "Can access 'invorderingscheck'"),
                    (
                        "access_sensitive_dossiers",
                        "Can read gevoelige dossiers (RIEC? / RIEPermisson)",
                    ),
                    ("access_sigital_surveillance", "Can read 'Digitaal toezicht'"),
                    (
                        "access_document_management_system",
                        "Can access 'DMS' (Alfresco / Decos)",
                    ),
                ],
            },
        ),
    ]
