# Generated by Django 4.2.14 on 2024-10-03 08:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("create_case", "Create a new Case"),
                    (
                        "create_digital_surveilance_case",
                        "Create a new 'Digitaal toezicht' Case",
                    ),
                    ("close_case", "Close a Case (by performing the last task)"),
                    ("perform_task", "Can perform a tasks"),
                    (
                        "access_personal_data_register",
                        "Can access 'BRP' (persoonsgegevens / ingeschreven personen)",
                    ),
                    (
                        "access_business_register",
                        "Can access 'Handelsregister' (bedrijfseigenaren van panden, bedrijfsinformatie)",
                    ),
                    ("access_recovery_check", "Can access 'invorderingscheck'"),
                    ("access_sensitive_dossiers", "Can read gevoelige dossiers"),
                    ("access_sigital_surveillance", "Can read 'Digitaal toezicht'"),
                    (
                        "access_document_management_system",
                        "Can access 'DMS' (Alfresco / Decos)",
                    ),
                ],
            },
        ),
    ]
