# Generated by Django 4.2.16 on 2025-04-22 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_delete_scopedtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopedViewToken",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "allowed_views",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of allowed view actions",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_view_auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoped Token",
                "verbose_name_plural": "Scoped Tokens",
            },
        ),
    ]
