# Generated by Django 5.2.5 on 2025-08-18 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_scopedviewtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scopedviewtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoped_auth_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
