version: "3.5"

services:
  zaak-gateway:
    env_file:
      - app/.env.local
  zaken_celery_worker:
    env_file:
      - app/.env.local
  zaken_celery_beat:
    env_file:
      - app/.env.local
  database:
    env_file:
      - postgres/.env.local
  rabbitmq:
    env_file:
      - rabbitmq/.env.local
