version: "3.5"

services:
  zaak-gateway:
    networks:
      - zaken_network
      - top_and_zaak_backend_bridge
    build: app
    hostname: zaak-gateway
    image: zaak-gateway
    ports:
      - 8080:8000
      - 5678:5678
    depends_on:
      - database
    env_file:
      - .env
    command: bash -c "/app/wait-for.sh database:5432 && /app/deploy/docker-entrypoint.development.sh"
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true

  database:
    networks:
      - zaken_network
    image: amsterdam/postgres11
    shm_size: "512m"
    ports:
      - "6409:5432"
    env_file:
      - .env
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  camunda:
    build: camunda/deployment
    hostname: camunda
    image: camunda-ritense
    ports:
      - 7000:8080
    env_file:
      - camunda/.env
    networks:
      - zaken_network

  camunda_db:
    image: amsterdam/postgres11
    networks:
      - zaken_network
    shm_size: "512m"
    ports:
      - "54321:5432"
    env_file:
      - camunda/.env
    volumes:
      - camunda-data:/var/lib/postgresql/data

networks:
  zaken_network:
    external: true
  top_and_zaak_backend_bridge:
    external: true

volumes:
  camunda-data:
  postgresql-data:
