version: '3.4'

services:
  web:
    build: app
    ports:
      - 8000:8000
    environment:
      - UWSGI_HTTP_SOCKET=0.0.0.0:8000
      - UWSGI_MASTER=1
      - UWSGI_CALLABLE=app
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=app
      - OPEN_ZAAK_CLIENT=client
      - OPEN_ZAAK_SECRET_KEY=secret_key
      - OPEN_ZAAK_PORT=8000
      - OPEN_ZAAK_API_VERSION=v1
      - OPEN_ZAAK_CONTAINER_NAME=openzaak.local
    volumes:
        - ./app:/app
    command: bash -c "uwsgi --py-auto-reload=1"
    depends_on:
      - openzaak.local
  db:
    image: mdillon/postgis
  redis:
    image: redis
  openzaak.local:
    image: openzaak/open-zaak
    environment:
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - SUBPATH=${SUBPATH:-/localhost}
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
    ports:
      - 8080:8000
    depends_on:
      - db
      - redis