version: '3.4'

services:
  app:
      build: app
      volumes:
          - .:/app
      ports:
          - 8000:8000
      depends_on:
          - database
          - openzaak.local
      environment:
          - OPEN_ZAAK_CLIENT=client
          - OPEN_ZAAK_SECRET_KEY=secret_key
          - OPEN_ZAAK_PORT=8000
          - OPEN_ZAAK_API_VERSION=v1
          - OPEN_ZAAK_CONTAINER_NAME=openzaak.local
  database:
    image: amsterdam/postgres11
    shm_size: '512m'
    ports:
      - "5409:5432"
    environment:
      POSTGRES_DB: zaken
      POSTGRES_USER: zaken
      POSTGRES_PASSWORD: insecure
  db:
    image: mdillon/postgis
  redis:
    image: redis
  openzaak.local:
    image: openzaak/open-zaak
    environment:
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - SUBPATH=${SUBPATH:-/localhost}
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
    ports:
      - 8080:8000
    depends_on:
      - db
      - redis
