
services:
  zaak-gateway:
    build: app
    hostname: zaak-gateway
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/zaken-backend}:${VERSION:-latest}
    ports:
      - 8080:8000
      - 5678:5678
    env_file:
      - .env
    stdin_open: true
    tty: true
