# Generated by Django 5.2.14 on 2026-09-28 08:26

import apps.puntenteller.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0007_alter_address_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kengetal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badkamer_toilet_hangend_factor",
                    models.DecimalField(decimal_places=2, default=2.75, max_digits=8),
                ),
                (
                    "badkamer_toilet_normaal_factor",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "badkamer_wastafel_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "badkamer_meerpersoons_wastafel_factor",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=8),
                ),
                (
                    "badkamer_douche_factor",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=8),
                ),
                (
                    "badkamer_bad_factor",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
                ),
                (
                    "badkamer_baddouche_factor",
                    models.DecimalField(decimal_places=2, default=6.0, max_digits=8),
                ),
                (
                    "badkamer_bubbelfunctie_bad_factor",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=8),
                ),
                (
                    "badkamer_volledige_afscheiding_douche_factor",
                    models.DecimalField(decimal_places=2, default=1.25, max_digits=8),
                ),
                (
                    "badkamer_handdoekenradiator_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "badkamer_kast_bij_wastafel_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "badkamer_kastruimte_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "badkamer_stopcontacten_factor",
                    models.DecimalField(decimal_places=2, default=0.25, max_digits=8),
                ),
                ("badkamer_stopcontacten_max", models.PositiveIntegerField(default=2)),
                (
                    "badkamer_eenhandsmengkraan_factor",
                    models.DecimalField(decimal_places=2, default=0.25, max_digits=8),
                ),
                (
                    "badkamer_thermostatische_mengkraan_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "keuken_aanrecht_grens_1",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_grens_2",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_grens_3",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_punten_1",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_punten_2",
                    models.DecimalField(decimal_places=2, default=4.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_punten_3",
                    models.DecimalField(decimal_places=2, default=7.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_afzuiginstallatie_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "keuken_inbouw_kookplaat_inductie_factor",
                    models.DecimalField(decimal_places=2, default=1.75, max_digits=8),
                ),
                (
                    "keuken_inbouw_kookplaat_keramisch_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_kookplaat_gas_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "keuken_inbouw_koelkast_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_vrieskast_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "keuken_inbouw_oven_elektrisch_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_oven_gas_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "keuken_inbouw_magnetron_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_vaatwasmachine_factor",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=8),
                ),
                (
                    "keuken_extra_kastruimte_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "keuken_eenhandsmengkraan_factor",
                    models.DecimalField(decimal_places=2, default=0.25, max_digits=8),
                ),
                (
                    "keuken_thermostatische_mengkraan_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "keuken_kokendwaterfunctie_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "apart_toilet_staand_factor",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=8),
                ),
                (
                    "apart_toilet_hangend_factor",
                    models.DecimalField(decimal_places=2, default=3.75, max_digits=8),
                ),
                (
                    "woonvoorziening_handicap_bedrag_per_punt",
                    models.DecimalField(decimal_places=2, default=332.0, max_digits=8),
                ),
                (
                    "sanitair_wastafel_niet_badkamer_max_punten",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "sanitair_meerpersoons_wastafel_niet_badkamer_max_punten",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=8),
                ),
                (
                    "vertrekken_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "overige_ruimte_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "verwarming_aantal_vertrekken_factor",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "verwarming_aantal_overige_ruimten_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "verwarming_aantal_overige_ruimten_max",
                    models.PositiveIntegerField(default=4),
                ),
                (
                    "verkoeling_aantal_vertrekken_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "verkoeling_aantal_vertrekken_max",
                    models.PositiveIntegerField(default=2),
                ),
                (
                    "buitenruimte_prive_basispunten",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "buitenruimte_prive_punten_per_m2",
                    models.DecimalField(decimal_places=2, default=0.35, max_digits=8),
                ),
                (
                    "buitenruimte_gemeenschappelijke_punten_per_m2",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "buitenruimte_max_punten",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=8),
                ),
                (
                    "buitenruimte_geen_buitenruimte_aftrek",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
                ),
                (
                    "parkeerruimte_gesloten_garage_bij_complex_factor",
                    models.DecimalField(decimal_places=2, default=9.0, max_digits=8),
                ),
                (
                    "parkeerruimte_buiten_bij_complex_met_dak_factor",
                    models.DecimalField(decimal_places=2, default=6.0, max_digits=8),
                ),
                (
                    "parkeerruimte_buiten_bij_complex_zonder_dak_factor",
                    models.DecimalField(decimal_places=2, default=4.0, max_digits=8),
                ),
                (
                    "woz_oppervlakte_parkeer_type_1",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=8),
                ),
                (
                    "bijzondere_voorziening_intercom_met_beeld_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "bijzondere_voorziening_laadpaal_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "zorgwoning_opslag_factor",
                    models.DecimalField(decimal_places=2, default=1.35, max_digits=4),
                ),
                (
                    "monument_rijksmonument_huurprijsopslag_factor",
                    models.DecimalField(decimal_places=2, default=1.35, max_digits=4),
                ),
                (
                    "monument_rijksmonument_extra_punten",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
                ),
                (
                    "monument_gemeentelijk_of_provinciaal_huurprijsopslag_factor",
                    models.DecimalField(decimal_places=2, default=1.15, max_digits=4),
                ),
                (
                    "monument_beschermd_stads_of_dorpsgezicht_huurprijsopslag_factor",
                    models.DecimalField(decimal_places=2, default=1.15, max_digits=4),
                ),
                (
                    "nieuwbouw_huurprijsopslag_factor",
                    models.DecimalField(decimal_places=2, default=1.1, max_digits=4),
                ),
                (
                    "energieprestatie_label_a4plus_eengezinswoning_punten",
                    models.SmallIntegerField(default=62),
                ),
                (
                    "energieprestatie_label_a4plus_meergezinswoning_punten",
                    models.SmallIntegerField(default=58),
                ),
                (
                    "energieprestatie_label_a3plus_eengezinswoning_punten",
                    models.SmallIntegerField(default=57),
                ),
                (
                    "energieprestatie_label_a3plus_meergezinswoning_punten",
                    models.SmallIntegerField(default=53),
                ),
                (
                    "energieprestatie_label_a2plus_eengezinswoning_punten",
                    models.SmallIntegerField(default=52),
                ),
                (
                    "energieprestatie_label_a2plus_meergezinswoning_punten",
                    models.SmallIntegerField(default=48),
                ),
                (
                    "energieprestatie_label_aplus_eengezinswoning_punten",
                    models.SmallIntegerField(default=47),
                ),
                (
                    "energieprestatie_label_aplus_meergezinswoning_punten",
                    models.SmallIntegerField(default=43),
                ),
                (
                    "energieprestatie_label_a_eengezinswoning_punten",
                    models.SmallIntegerField(default=41),
                ),
                (
                    "energieprestatie_label_a_meergezinswoning_punten",
                    models.SmallIntegerField(default=37),
                ),
                (
                    "energieprestatie_label_b_eengezinswoning_punten",
                    models.SmallIntegerField(default=34),
                ),
                (
                    "energieprestatie_label_b_meergezinswoning_punten",
                    models.SmallIntegerField(default=30),
                ),
                (
                    "energieprestatie_label_c_eengezinswoning_punten",
                    models.SmallIntegerField(default=22),
                ),
                (
                    "energieprestatie_label_c_meergezinswoning_punten",
                    models.SmallIntegerField(default=15),
                ),
                (
                    "energieprestatie_label_d_eengezinswoning_punten",
                    models.SmallIntegerField(default=14),
                ),
                (
                    "energieprestatie_label_d_meergezinswoning_punten",
                    models.SmallIntegerField(default=11),
                ),
                (
                    "energieprestatie_label_e_eengezinswoning_punten",
                    models.SmallIntegerField(default=-4),
                ),
                (
                    "energieprestatie_label_e_meergezinswoning_punten",
                    models.SmallIntegerField(default=-4),
                ),
                (
                    "energieprestatie_label_f_eengezinswoning_punten",
                    models.SmallIntegerField(default=-9),
                ),
                (
                    "energieprestatie_label_f_meergezinswoning_punten",
                    models.SmallIntegerField(default=-9),
                ),
                (
                    "energieprestatie_label_g_eengezinswoning_punten",
                    models.SmallIntegerField(default=-15),
                ),
                (
                    "energieprestatie_label_g_meergezinswoning_punten",
                    models.SmallIntegerField(default=-15),
                ),
                (
                    "energieprestatie_ei_grens_1",
                    models.DecimalField(decimal_places=2, default=0.6, max_digits=4),
                ),
                (
                    "energieprestatie_ei_grens_2",
                    models.DecimalField(decimal_places=2, default=0.8, max_digits=4),
                ),
                (
                    "energieprestatie_ei_grens_3",
                    models.DecimalField(decimal_places=2, default=1.2, max_digits=4),
                ),
                (
                    "energieprestatie_ei_grens_4",
                    models.DecimalField(decimal_places=2, default=1.4, max_digits=4),
                ),
                (
                    "energieprestatie_ei_grens_5",
                    models.DecimalField(decimal_places=2, default=1.8, max_digits=4),
                ),
                (
                    "energieprestatie_ei_grens_6",
                    models.DecimalField(decimal_places=2, default=2.1, max_digits=4),
                ),
                (
                    "energieprestatie_ei_grens_7",
                    models.DecimalField(decimal_places=2, default=2.4, max_digits=4),
                ),
                (
                    "energieprestatie_ei_grens_8",
                    models.DecimalField(decimal_places=2, default=2.7, max_digits=4),
                ),
                (
                    "energieprestatie_ei_punten_1_eengezinswoning",
                    models.SmallIntegerField(default=52),
                ),
                (
                    "energieprestatie_ei_punten_1_meergezinswoning",
                    models.SmallIntegerField(default=48),
                ),
                (
                    "energieprestatie_ei_punten_2_eengezinswoning",
                    models.SmallIntegerField(default=47),
                ),
                (
                    "energieprestatie_ei_punten_2_meergezinswoning",
                    models.SmallIntegerField(default=43),
                ),
                (
                    "energieprestatie_ei_punten_3_eengezinswoning",
                    models.SmallIntegerField(default=41),
                ),
                (
                    "energieprestatie_ei_punten_3_meergezinswoning",
                    models.SmallIntegerField(default=37),
                ),
                (
                    "energieprestatie_ei_punten_4_eengezinswoning",
                    models.SmallIntegerField(default=34),
                ),
                (
                    "energieprestatie_ei_punten_4_meergezinswoning",
                    models.SmallIntegerField(default=30),
                ),
                (
                    "energieprestatie_ei_punten_5_eengezinswoning",
                    models.SmallIntegerField(default=22),
                ),
                (
                    "energieprestatie_ei_punten_5_meergezinswoning",
                    models.SmallIntegerField(default=15),
                ),
                (
                    "energieprestatie_ei_punten_6_eengezinswoning",
                    models.SmallIntegerField(default=14),
                ),
                (
                    "energieprestatie_ei_punten_6_meergezinswoning",
                    models.SmallIntegerField(default=11),
                ),
                (
                    "energieprestatie_ei_punten_7_eengezinswoning",
                    models.SmallIntegerField(default=-4),
                ),
                (
                    "energieprestatie_ei_punten_7_meergezinswoning",
                    models.SmallIntegerField(default=-4),
                ),
                (
                    "energieprestatie_ei_punten_8_eengezinswoning",
                    models.SmallIntegerField(default=-9),
                ),
                (
                    "energieprestatie_ei_punten_8_meergezinswoning",
                    models.SmallIntegerField(default=-9),
                ),
                (
                    "energieprestatie_ei_punten_9_eengezinswoning",
                    models.SmallIntegerField(default=-15),
                ),
                (
                    "energieprestatie_ei_punten_9_meergezinswoning",
                    models.SmallIntegerField(default=-15),
                ),
                (
                    "energieprestatie_bouwjaar_grens_1",
                    models.PositiveSmallIntegerField(default=2002),
                ),
                (
                    "energieprestatie_bouwjaar_grens_2",
                    models.PositiveSmallIntegerField(default=2000),
                ),
                (
                    "energieprestatie_bouwjaar_grens_3",
                    models.PositiveSmallIntegerField(default=1992),
                ),
                (
                    "energieprestatie_bouwjaar_grens_4",
                    models.PositiveSmallIntegerField(default=1984),
                ),
                (
                    "energieprestatie_bouwjaar_grens_5",
                    models.PositiveSmallIntegerField(default=1979),
                ),
                (
                    "energieprestatie_bouwjaar_grens_6",
                    models.PositiveSmallIntegerField(default=1977),
                ),
                (
                    "energieprestatie_bouwjaar_punten_1_eengezinswoning",
                    models.SmallIntegerField(default=41),
                ),
                (
                    "energieprestatie_bouwjaar_punten_1_meergezinswoning",
                    models.SmallIntegerField(default=37),
                ),
                (
                    "energieprestatie_bouwjaar_punten_2_eengezinswoning",
                    models.SmallIntegerField(default=34),
                ),
                (
                    "energieprestatie_bouwjaar_punten_2_meergezinswoning",
                    models.SmallIntegerField(default=30),
                ),
                (
                    "energieprestatie_bouwjaar_punten_3_eengezinswoning",
                    models.SmallIntegerField(default=22),
                ),
                (
                    "energieprestatie_bouwjaar_punten_3_meergezinswoning",
                    models.SmallIntegerField(default=15),
                ),
                (
                    "energieprestatie_bouwjaar_punten_4_eengezinswoning",
                    models.SmallIntegerField(default=14),
                ),
                (
                    "energieprestatie_bouwjaar_punten_4_meergezinswoning",
                    models.SmallIntegerField(default=11),
                ),
                (
                    "energieprestatie_bouwjaar_punten_5_eengezinswoning",
                    models.SmallIntegerField(default=-4),
                ),
                (
                    "energieprestatie_bouwjaar_punten_5_meergezinswoning",
                    models.SmallIntegerField(default=-4),
                ),
                (
                    "energieprestatie_bouwjaar_punten_6_eengezinswoning",
                    models.SmallIntegerField(default=-9),
                ),
                (
                    "energieprestatie_bouwjaar_punten_6_meergezinswoning",
                    models.SmallIntegerField(default=-9),
                ),
                (
                    "energieprestatie_bouwjaar_punten_7_eengezinswoning",
                    models.SmallIntegerField(default=-15),
                ),
                (
                    "energieprestatie_bouwjaar_punten_7_meergezinswoning",
                    models.SmallIntegerField(default=-15),
                ),
                (
                    "energieprestatie_epv_eengezinswoning_punten",
                    models.SmallIntegerField(default=32),
                ),
                (
                    "energieprestatie_epv_meergezinswoning_punten",
                    models.SmallIntegerField(default=28),
                ),
                ("woz_kengetallen_per_peiljaar", models.JSONField(default=dict)),
                (
                    "woz_gemiddelde_regio_per_m2",
                    models.DecimalField(decimal_places=2, default=7111.0, max_digits=8),
                ),
                (
                    "woz_percentage_grens",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "woz_punten_boven_grens",
                    models.DecimalField(decimal_places=2, default=14.0, max_digits=8),
                ),
                (
                    "woz_punten_binnen_grens",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=8),
                ),
                (
                    "woz_punten_onder_grens",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Gebruikersinvoer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "vertrekken",
                    models.JSONField(
                        blank=True,
                        default=apps.puntenteller.models.default_extra_ruimten,
                    ),
                ),
                (
                    "overige_ruimten",
                    models.JSONField(
                        blank=True,
                        default=apps.puntenteller.models.default_extra_ruimten,
                    ),
                ),
                (
                    "verkeersruimten",
                    models.JSONField(
                        blank=True,
                        default=apps.puntenteller.models.default_extra_ruimten,
                    ),
                ),
                (
                    "buitenruimten",
                    models.JSONField(
                        blank=True,
                        default=apps.puntenteller.models.default_extra_ruimten,
                    ),
                ),
                (
                    "parkeerruimten",
                    models.JSONField(
                        blank=True,
                        default=apps.puntenteller.models.default_extra_ruimten,
                    ),
                ),
                (
                    "energielabel_klasse",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "energie_index",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("is_eengezinswoning", models.BooleanField(blank=True, null=True)),
                (
                    "heeft_energieprestatievergoeding",
                    models.BooleanField(default=False),
                ),
                ("bouwjaar", models.PositiveIntegerField(blank=True, null=True)),
                ("gebruiksoppervlakte", models.PositiveIntegerField(default=0)),
                ("woz_waarde", models.PositiveIntegerField(default=0)),
                ("woz_peildatum_jaar", models.PositiveIntegerField(default=2025)),
                ("woz_kleine_nieuwbouwwoning", models.BooleanField(default=False)),
                ("woz_nieuwbouw_2015_2019", models.BooleanField(default=False)),
                (
                    "woz_bouwvoltooiingspercentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("woonvoorziening_handicap", models.BooleanField(default=False)),
                (
                    "woonvoorziening_handicap_netto_investering",
                    models.PositiveIntegerField(default=0),
                ),
                ("monument", models.BooleanField(default=False)),
                (
                    "monument_soort",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "huurovereenkomst_afgesloten_op",
                    models.DateField(blank=True, null=True),
                ),
                ("zorgwoning", models.BooleanField(default=False)),
                ("nieuwbouw", models.BooleanField(default=False)),
                (
                    "bijzondere_voorziening_intercom_met_beeld",
                    models.BooleanField(default=False),
                ),
                (
                    "bijzondere_voorziening_laadpalen",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "adres",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntenteller_gebruikersinvoer",
                        to="addresses.address",
                    ),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntenteller_gebruikersinvoer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
