# Generated by Django 5.2.14 on 2026-08-06 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0007_alter_address_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gebruikersinvoer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("badkamer_aantal_adressen", models.PositiveIntegerField(default=0)),
                ("badkamer_toilet_hangend", models.PositiveIntegerField(default=0)),
                ("badkamer_toilet_normaal", models.PositiveIntegerField(default=0)),
                ("badkamer_wastafel", models.PositiveIntegerField(default=0)),
                (
                    "badkamer_meerpersoons_wastafel",
                    models.PositiveIntegerField(default=0),
                ),
                ("badkamer_douche", models.PositiveIntegerField(default=0)),
                ("badkamer_bad", models.PositiveIntegerField(default=0)),
                ("badkamer_baddouche", models.PositiveIntegerField(default=0)),
                ("badkamer_bubbelfunctie_bad", models.PositiveIntegerField(default=0)),
                (
                    "badkamer_volledige_afscheiding_douche",
                    models.PositiveIntegerField(default=0),
                ),
                ("badkamer_handdoekenradiator", models.PositiveIntegerField(default=0)),
                ("badkamer_kast_bij_wastafel", models.PositiveIntegerField(default=0)),
                ("badkamer_kastruimte", models.PositiveIntegerField(default=0)),
                ("badkamer_stopcontacten", models.PositiveIntegerField(default=0)),
                ("badkamer_eenhandsmengkraan", models.PositiveIntegerField(default=0)),
                (
                    "badkamer_thermostatische_mengkraan",
                    models.PositiveIntegerField(default=0),
                ),
                ("keuken_aantal_adressen", models.PositiveIntegerField(default=0)),
                (
                    "keuken_aanrechtlengte_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "keuken_inbouw_afzuiginstallatie",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "keuken_inbouw_kookplaat_inductie",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "keuken_inbouw_kookplaat_keramisch",
                    models.PositiveIntegerField(default=0),
                ),
                ("keuken_inbouw_kookplaat_gas", models.PositiveIntegerField(default=0)),
                ("keuken_inbouw_koelkast", models.PositiveIntegerField(default=0)),
                ("keuken_inbouw_vrieskast", models.PositiveIntegerField(default=0)),
                (
                    "keuken_inbouw_oven_elektrisch",
                    models.PositiveIntegerField(default=0),
                ),
                ("keuken_inbouw_oven_gas", models.PositiveIntegerField(default=0)),
                ("keuken_inbouw_magnetron", models.PositiveIntegerField(default=0)),
                (
                    "keuken_inbouw_vaatwasmachine",
                    models.PositiveIntegerField(default=0),
                ),
                ("keuken_extra_kastruimte", models.PositiveIntegerField(default=0)),
                ("keuken_eenhandsmengkraan", models.PositiveIntegerField(default=0)),
                (
                    "keuken_thermostatische_mengkraan",
                    models.PositiveIntegerField(default=0),
                ),
                ("keuken_kokendwaterfunctie", models.PositiveIntegerField(default=0)),
                ("apart_toilet_staand", models.PositiveIntegerField(default=0)),
                ("apart_toilet_hangend", models.PositiveIntegerField(default=0)),
                (
                    "vertrekken_oppervlakte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("vertrekken_1", models.PositiveIntegerField(default=0)),
                ("vertrekken_2", models.PositiveIntegerField(default=0)),
                ("vertrekken_3", models.PositiveIntegerField(default=0)),
                ("vertrekken_4", models.PositiveIntegerField(default=0)),
                ("vertrekken_5", models.PositiveIntegerField(default=0)),
                ("vertrekken_6", models.PositiveIntegerField(default=0)),
                (
                    "overige_ruimte_oppervlakte",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("overige_ruimte_1", models.PositiveIntegerField(default=0)),
                ("overige_ruimte_2", models.PositiveIntegerField(default=0)),
                ("overige_ruimte_3", models.PositiveIntegerField(default=0)),
                ("overige_ruimte_4", models.PositiveIntegerField(default=0)),
                ("overige_ruimte_5", models.PositiveIntegerField(default=0)),
                (
                    "verwarming_aantal_vertrekken",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "verwarming_aantal_overige_ruimten",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "verkoeling_aantal_vertrekken",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "buitenruimte_prive_buitenruimte",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "buitenruimte_gemeenschappelijke_buitenruimte",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "parkeerruimte_gesloten_garage_bij_complex",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "parkeerruimte_buiten_bij_complex_met_dak",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "parkeerruimte_buiten_bij_complex_zonder_dak",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "energielabel_klasse",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("woz_waarde", models.PositiveIntegerField(default=0)),
                ("woz_peildatum_jaar", models.PositiveIntegerField(default=2025)),
                ("monument", models.BooleanField(default=False)),
                (
                    "monument_soort",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bijzondere_voorziening_intercom_met_beeld",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "bijzondere_voorziening_laadpaal",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "adres",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntenteller_gebruikersinvoer",
                        to="addresses.address",
                    ),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puntenteller_gebruikersinvoer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
