# Generated by Django 5.2.14 on 2026-08-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntenteller", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kengetal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badkamer_toilet_hangend_factor",
                    models.DecimalField(decimal_places=2, default=2.75, max_digits=8),
                ),
                (
                    "badkamer_toilet_normaal_factor",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "badkamer_wastafel_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "badkamer_meerpersoons_wastafel_factor",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=8),
                ),
                (
                    "badkamer_douche_factor",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=8),
                ),
                (
                    "badkamer_bad_factor",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
                ),
                (
                    "badkamer_baddouche_factor",
                    models.DecimalField(decimal_places=2, default=6.0, max_digits=8),
                ),
                (
                    "badkamer_bubbelfunctie_bad_factor",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=8),
                ),
                (
                    "badkamer_volledige_afscheiding_douche_factor",
                    models.DecimalField(decimal_places=2, default=1.25, max_digits=8),
                ),
                (
                    "badkamer_handdoekenradiator_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "badkamer_kast_bij_wastafel_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "badkamer_kastruimte_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "badkamer_stopcontacten_factor",
                    models.DecimalField(decimal_places=2, default=0.25, max_digits=8),
                ),
                ("badkamer_stopcontacten_max", models.PositiveIntegerField(default=2)),
                (
                    "badkamer_eenhandsmengkraan_factor",
                    models.DecimalField(decimal_places=2, default=0.25, max_digits=8),
                ),
                (
                    "badkamer_thermostatische_mengkraan_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "keuken_aanrecht_grens_1",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_grens_2",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_grens_3",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_grens_4",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_punten_1",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_punten_2",
                    models.DecimalField(decimal_places=2, default=4.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_punten_3",
                    models.DecimalField(decimal_places=2, default=7.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_punten_4",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
                ),
                (
                    "keuken_aanrecht_punten_5",
                    models.DecimalField(decimal_places=2, default=13.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_afzuiginstallatie_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "keuken_inbouw_kookplaat_inductie_factor",
                    models.DecimalField(decimal_places=2, default=1.75, max_digits=8),
                ),
                (
                    "keuken_inbouw_kookplaat_keramisch_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_kookplaat_gas_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "keuken_inbouw_koelkast_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_vrieskast_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "keuken_inbouw_oven_elektrisch_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_oven_gas_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "keuken_inbouw_magnetron_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "keuken_inbouw_vaatwasmachine_factor",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=8),
                ),
                (
                    "keuken_extra_kastruimte_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "keuken_eenhandsmengkraan_factor",
                    models.DecimalField(decimal_places=2, default=0.25, max_digits=8),
                ),
                (
                    "keuken_thermostatische_mengkraan_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "keuken_kokendwaterfunctie_factor",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=8),
                ),
                (
                    "apart_toilet_staand_factor",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=8),
                ),
                (
                    "apart_toilet_hangend_factor",
                    models.DecimalField(decimal_places=2, default=3.75, max_digits=8),
                ),
                (
                    "vertrekken_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "overige_ruimte_factor",
                    models.DecimalField(decimal_places=2, default=0.75, max_digits=8),
                ),
                (
                    "verwarming_aantal_vertrekken_factor",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "verwarming_aantal_overige_ruimten_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "verwarming_aantal_overige_ruimten_max",
                    models.PositiveIntegerField(default=4),
                ),
                (
                    "verkoeling_aantal_vertrekken_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "verkoeling_aantal_vertrekken_max",
                    models.PositiveIntegerField(default=2),
                ),
                (
                    "buitenruimte_prive_buitenruimte_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "buitenruimte_gemeenschappelijke_buitenruimte_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "buitenruimte_geen_gemeenschappelijke_aftrek",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
                ),
                (
                    "parkeerruimte_gesloten_garage_bij_complex_factor",
                    models.DecimalField(decimal_places=2, default=9.0, max_digits=8),
                ),
                (
                    "parkeerruimte_buiten_bij_complex_met_dak_factor",
                    models.DecimalField(decimal_places=2, default=6.0, max_digits=8),
                ),
                (
                    "parkeerruimte_buiten_bij_complex_zonder_dak_factor",
                    models.DecimalField(decimal_places=2, default=4.0, max_digits=8),
                ),
                (
                    "bijzondere_voorziening_intercom_met_beeld_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
                (
                    "bijzondere_voorziening_laadpaal_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
