# Generated by Django 5.2.14 on 2026-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntenteller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gebruikersinvoer",
            name="woonvoorziening_handicap_netto_investering",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
