# Generated by Django 5.2.14 on 2026-08-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puntenteller", "0002_kengetal"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="gebruiksoppervlakte",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kengetal",
            name="woz_gemiddelde_regio_per_m2",
            field=models.DecimalField(decimal_places=2, default=7111.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="kengetal",
            name="woz_percentage_grens",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="kengetal",
            name="woz_punten_binnen_grens",
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="kengetal",
            name="woz_punten_boven_grens",
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="kengetal",
            name="woz_punten_onder_grens",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
        ),
        migrations.AlterModelOptions(
            name="kengetal",
            options={"ordering": ["-id"]},
        ),
    ]
