# Generated by Django 5.2.14 on 2026-09-14 00:00

from django.db import migrations, models

DEFAULT_WOZ_KENGETALLEN_PER_PEILJAAR = {
    "2025": {"onderdeel_1": "16954", "onderdeel_2": "268"},
    "2024": {"onderdeel_1": "15329", "onderdeel_2": "242"},
    "2023": {"onderdeel_1": "14543", "onderdeel_2": "229"},
    "2022": {"onderdeel_1": "14146", "onderdeel_2": "222"},
}


class Migration(migrations.Migration):

    dependencies = [
        ("puntenteller", "0003_gebruiksoppervlakte_en_woz_punten"),
    ]

    operations = [
        migrations.AddField(
            model_name="kengetal",
            name="woz_kengetallen_per_peiljaar",
            field=models.JSONField(default=DEFAULT_WOZ_KENGETALLEN_PER_PEILJAAR),
        ),
    ]
