# Generated by Django 5.2.14 on 2026-09-14 00:00

from django.db import migrations, models


def vul_woz_kleine_nieuwbouwkengetallen(apps, schema_editor):
    Kengetal = apps.get_model("puntenteller", "Kengetal")
    defaults = {
        "2025": {"onderdeel_2_kleine_nieuwbouwwoning": "114"},
        "2024": {"onderdeel_2_kleine_nieuwbouwwoning": "103"},
        "2023": {"onderdeel_2_kleine_nieuwbouwwoning": "97"},
        "2022": {"onderdeel_2_kleine_nieuwbouwwoning": "94"},
    }

    for kengetal in Kengetal.objects.all():
        bestaande_waarde = kengetal.woz_kengetallen_per_peiljaar or {}
        gewijzigd = False
        for peiljaar, aanvullingen in defaults.items():
            jaarwaarden = dict(bestaande_waarde.get(peiljaar, {}))
            for sleutel, waarde in aanvullingen.items():
                if sleutel not in jaarwaarden:
                    jaarwaarden[sleutel] = waarde
                    gewijzigd = True
            bestaande_waarde[peiljaar] = jaarwaarden
        if gewijzigd:
            kengetal.woz_kengetallen_per_peiljaar = bestaande_waarde
            kengetal.save(update_fields=["woz_kengetallen_per_peiljaar"])


class Migration(migrations.Migration):

    dependencies = [
        ("puntenteller", "0004_kengetal_woz_kengetallen_per_peiljaar"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="woz_bouwvoltooiingspercentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="woz_kleine_nieuwbouwwoning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="woz_nieuwbouw_2015_2019",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            vul_woz_kleine_nieuwbouwkengetallen,
            migrations.RunPython.noop,
        ),
    ]
