# Just some const for prototyping, will be revised later

BED_AND_BREAKFAST = "Bed en breakfast 2019"
BURGWALLEN_PROJECT_OUDEZIJDE = "Burgwallenproject Oudezijde"
CORPO_RICO = "Corpo-rico"
DIGITAAL_TOEZICHT_SAFARI = "Digital toezicht Safari"
DIGITAAL_TOEZICHT_ZEBRA = "Digital toezicht Zebra"
HAARLEMMERBUURT = "Haarlemmerbuurt"
HOTLINE = "Hotline"
MYSTERY_GUEST = "Mystery Guest"
PROJECT_ANDES = "Project Andes"
PROJECT_JORDAAN = "Project Jordaan"
PROJECT_LOBITH = "Project Lobith"
PROJECT_SAHARA = "Project Sahara"
SAFARI = "Safari"
PROJECT_SAFARI_2015 = "Safari 2015"
SAHARA_ADAMS_SUITES = "Sahara Adams Suites"
SAHARA_HELE_WONING = "Sahara hele woning"
SAHARA_MEER_DAN_4 = "Sahara meer dan 4"
SAHARA_RECENSIES = "Sahara Recensies"
SAHARA_VEEL_ADV = "Sahara veel adv"
PROJECT_SOCIAL_MEDIA_2019 = "Social Media 2019"
PROJECT_WOONSCHIP = "Woonschip (woonboot)"
PROJECT_ZEBRA = "Zebra"

PROJECTS = [
    BED_AND_BREAKFAST,
    BURGWALLEN_PROJECT_OUDEZIJDE,
    CORPO_RICO,
    DIGITAAL_TOEZICHT_SAFARI,
    DIGITAAL_TOEZICHT_ZEBRA,
    HAARLEMMERBUURT,
    HOTLINE,
    MYSTERY_GUEST,
    PROJECT_ANDES,
    PROJECT_JORDAAN,
    PROJECT_LOBITH,
    PROJECT_SAHARA,
    SAFARI,
    PROJECT_SAFARI_2015,
    SAHARA_ADAMS_SUITES,
    SAHARA_HELE_WONING,
    SAHARA_MEER_DAN_4,
    SAHARA_RECENSIES,
    SAHARA_VEEL_ADV,
    PROJECT_SOCIAL_MEDIA_2019,
    PROJECT_WOONSCHIP,
    PROJECT_ZEBRA,
]

ONDERZOEK_BUITENDIENST = "Onderzoek buitendienst"
TWEEDE_CONTROLE = "2de Controle"
DERDE_CONTROLE = "3de Controle"
HERCONTROLE = "Hercontrole"
TWEEDE_HERCONTROLE = "2de hercontrole"
DERDE_HERCONTROLE = "3de hercontrole"
AVONDRONDE = "Avondronde"
ONDERZOEK_ADVERTENTIE = "Onderzoek advertentie"
WEEKEND_BUITENDIENST_ONDERZOEK = "Weekend buitendienstonderzoek"
ISSUEMELDING = "Issuemelding"

STADIA = [
    ONDERZOEK_BUITENDIENST,
    TWEEDE_CONTROLE,
    DERDE_CONTROLE,
    HERCONTROLE,
    TWEEDE_HERCONTROLE,
    DERDE_HERCONTROLE,
    AVONDRONDE,
    ONDERZOEK_ADVERTENTIE,
    WEEKEND_BUITENDIENST_ONDERZOEK,
    ISSUEMELDING,
]
