name: zaken-backend
tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

labels:
  app: zaken-backend

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  tag: latest

network:
  allow-ingress:
    selector: app == 'zaken-backend'
    ingress:
      - action: Allow
    egress:
      - action: Allow

serviceAccount: app
serviceAccounts:
  app: {}

secrets:
  certificate:
    type: keyvault
    tls: wonen

deployments:
  zaken-backend:
    image:
      repository: salmagundi/zaken-backend
    securityContext:
      runAsUser: 101
    selectorLabels:
      component: zaken-backend
    containers:
      - name: main
        ports:
          - port: 8080
            name: http
    tempDirs:
      - /static

  zaken-celery-worker:
    image:
      repository: salmagundi/zaken-backend
    selectorLabels:
      component: zaken-celery-worker
    containers:
      - name: main
        command:
          - celery
        args:
          - "-A"
          - "config"
          - "worker"
          - "-l"
          - "info"
          - "-Q"
          - "AZA"
    tempDirs:
      - /tmp
      - /static

  zaken-celery-beat:
    image:
      repository: salmagundi/zaken-backend
    selectorLabels:
      component: zaken-celery-beat
    containers:
      - name: main
        command:
          - celery
        args:
          - "-A"
          - "config"
          - "beat"
          - "-l"
          - "info"
          - "--scheduler"
          - "django_celery_beat.schedulers:DatabaseScheduler"
    tempDirs:
      - /tmp
      - /static

services:
  zaken-backend:
    selector:
      component: zaken-backend
    ports:
      - port: 8080
        targetPort: 8080

ingress:
  zaken-backend-internal:
    className: nginx-internal
    paths:
      - path: /
        pathType: Prefix
        service: zaken-backend
        port: 8080
    tls: certificate

jobs:
  certificate-init:
    image:
      repository: salmagundi/zaken-backend
    annotations:
      helm.sh/hook: post-install,post-upgrade
    labels:
      component: certificate
    secrets:
      - certificate
    containers:
      - name: main
        command:
          - sleep
        args:
          - "1"
