# Generated by Django 3.2.7 on 2021-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summonedperson",
            name="person_role",
            field=models.CharField(
                choices=[
                    ("PERSON_ROLE_OWNER", "PERSON_ROLE_OWNER"),
                    ("PERSON_ROLE_RESIDENT", "PERSON_ROLE_RESIDENT"),
                    ("PERSON_ROLE_MIDDLEMAN", "PERSON_ROLE_MIDDLEMAN"),
                    ("PERSON_ROLE_PLATFORM", "PERSON_ROLE_PLATFORM"),
                ],
                default="PERSON_ROLE_OWNER",
                max_length=255,
            ),
        ),
    ]
