# Generated by Django 3.1.5 on 2021-02-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0039_auto_20210204_1438"),
        ("summons", "0003_summon_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="summonedperson",
            name="summon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons",
                to="summons.summon",
            ),
        ),
        migrations.AlterField(
            model_name="summontype",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summon_types",
                to="cases.caseteam",
            ),
        ),
    ]
