# Generated by Django 3.1.7 on 2021-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summons", "0005_summontype_camunda_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="summon",
            name="intention_closing_decision",
            field=models.BooleanField(default=False),
        ),
    ]
