# Generated by Django 3.1.7 on 2021-03-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summons", "0006_summon_intention_closing_decision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summon",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="summon",
            name="intention_closing_decision",
            field=models.BooleanField(),
        ),
    ]
