# Generated by Django 3.1.8 on 2021-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summons", "0014_summonedperson_person_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summonedperson",
            name="person_role",
            field=models.CharField(
                choices=[
                    ("PERSON_ROLE_OWNER", "PERSON_ROLE_OWNER"),
                    ("PERSON_ROLE_RESIDENT", "PERSON_ROLE_RESIDENT"),
                    ("PERSON_ROLE_MIDDLEMAN", "PERSON_ROLE_MIDDLEMAN"),
                ],
                default="PERSON_ROLE_OWNER",
                max_length=255,
            ),
        ),
    ]
