# Generated by Django 3.2.7 on 2021-10-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summons", "0015_auto_20210712_1204"),
    ]

    operations = [
        migrations.RenameField(
            model_name="summon",
            old_name="camunda_task_id",
            new_name="case_user_task_id",
        ),
    ]
