# Generated by Django 3.2.7 on 2022-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_schedule_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="visit_from_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
