# Generated by Django 3.1.7 on 2021-03-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0042_auto_20210224_2009"),
        ("schedules", "0003_auto_20210318_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="cases.caseteam",
            ),
        ),
    ]
