# Generated by Django 3.1.7 on 2021-03-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0042_auto_20210224_2009"),
        ("schedules", "0003_auto_20210318_1559"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="schedule_type",
            new_name="action",
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("case", "action")},
        ),
    ]
