# Generated by Django 3.2.7 on 2022-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_schedule_visit_from_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="housing_corporation_combiteam",
            field=models.BooleanField(default=False),
        ),
    ]
