# Generated by Django 3.2.13 on 2024-02-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_schedule_housing_corporation_combiteam"),
    ]

    operations = []
