# Generated by Django 3.1.7 on 2021-03-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_auto_20210318_1608"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together=set(),
        ),
    ]
