# Generated by Django 3.2.13 on 2024-02-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_alter_default_column_ids_azure"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            DECLARE
                max_id BIGINT;
            BEGIN
                -- Find the maximum id value in the table
                SELECT MAX(id) INTO max_id FROM public.schedules_action;

                -- If there are no records, set max_id to 0
                IF max_id IS NULL THEN
                    max_id := 0;
                END IF;
                EXECUTE FORMAT('ALTER SEQUENCE public.schedules_action_id_seq RESTART WITH %s;', max_id + 1);
            END $$;
        """
        )
    ]
