# Generated by Django 3.1.7 on 2021-03-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_auto_20210329_2046"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="priority",
            options={"ordering": ["weight"]},
        ),
    ]
