# Generated by Django 4.2.23 on 2025-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_update_sequence_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_additional",
            field=models.BooleanField(default=False),
        ),
    ]
