# Generated by Django 3.1.7 on 2021-05-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0007_auto_20210331_1949"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="camunda_task_id",
            field=models.CharField(default="-1", max_length=50),
        ),
    ]
