# Generated by Django 3.1.8 on 2021-05-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0056_auto_20210525_1424"),
        ("schedules", "0009_auto_20210520_1136"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="team",
            new_name="theme",
        ),
        migrations.RenameField(
            model_name="daysegment",
            old_name="team",
            new_name="theme",
        ),
        migrations.RenameField(
            model_name="priority",
            old_name="team",
            new_name="theme",
        ),
        migrations.RenameField(
            model_name="weeksegment",
            old_name="team",
            new_name="theme",
        ),
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("name", "theme")},
        ),
        migrations.AlterUniqueTogether(
            name="daysegment",
            unique_together={("name", "theme")},
        ),
        migrations.AlterUniqueTogether(
            name="priority",
            unique_together={("name", "theme")},
        ),
        migrations.AlterUniqueTogether(
            name="weeksegment",
            unique_together={("name", "theme")},
        ),
    ]
