# Generated by Django 3.1.8 on 2021-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0010_auto_20210525_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
