# Generated by Django 3.1.7 on 2021-03-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("summons", "0008_remove_summon_intention_closing_decision"),
        ("cases", "0042_auto_20210224_2009"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camunda_option", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_sanction", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_types",
                        to="cases.caseteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="cases.case",
                    ),
                ),
                (
                    "decision_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="decisions.decisiontype",
                    ),
                ),
                (
                    "summon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision",
                        to="summons.summon",
                    ),
                ),
            ],
        ),
    ]
