# Generated by Django 3.1.7 on 2021-03-17 09:57

from django.db import migrations


class Migration(migrations.Migration):
    def create_decision_types(apps, schema_editor):
        DecisionType = apps.get_model("decisions", "DecisionType")
        CaseTeam = apps.get_model("cases", "CaseTeam")

        (team, _) = CaseTeam.objects.get_or_create(name="Vakantieverhuur")

        decision_type_1 = DecisionType()
        decision_type_1.camunda_option = "boete"
        decision_type_1.name = "Boete"
        decision_type_1.is_sanction = False
        decision_type_1.team = team
        decision_type_1.save()

        decision_type_2 = DecisionType()
        decision_type_2.camunda_option = "invordering_dwangsom"
        decision_type_2.name = "Invordering dwangsom"
        decision_type_2.is_sanction = False
        decision_type_2.team = team
        decision_type_2.save()

        decision_type_3 = DecisionType()
        decision_type_3.camunda_option = "meldplicht_beschikking_boete"
        decision_type_3.name = "Meldplicht beschikking dwangsom"
        decision_type_3.is_sanction = False
        decision_type_3.team = team
        decision_type_3.save()

        decision_type_4 = DecisionType()
        decision_type_4.camunda_option = "preventieve_last"
        decision_type_4.name = "Preventieve last"
        decision_type_4.is_sanction = False
        decision_type_4.team = team
        decision_type_4.save()

        decision_type_5 = DecisionType()
        decision_type_5.camunda_option = "last_onder_dwangsom"
        decision_type_5.name = "Last onder dwangsom"
        decision_type_5.is_sanction = False
        decision_type_5.team = team
        decision_type_5.save()

        decision_type_6 = DecisionType()
        decision_type_6.camunda_option = "intrekken_vv_vergunning"
        decision_type_6.name = "Intrekken VV vergunning"
        decision_type_6.is_sanction = False
        decision_type_6.team = team
        decision_type_6.save()

        decision_type_7 = DecisionType()
        decision_type_7.camunda_option = "intrekken_bb_vergunning"
        decision_type_7.name = "Intrekken BB vergunning"
        decision_type_7.is_sanction = False
        decision_type_7.team = team
        decision_type_7.save()

        decision_type_8 = DecisionType()
        decision_type_8.camunda_option = "intrekken_shortstay_vergunning"
        decision_type_8.name = "Intrekken Shortstay vergunning"
        decision_type_8.is_sanction = False
        decision_type_8.team = team
        decision_type_8.save()

    dependencies = [
        ("decisions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_decision_types, migrations.RunPython.noop),
    ]
