# Generated by Django 3.2.7 on 2022-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="nuisance_detected",
            field=models.BooleanField(default=False),
        ),
    ]
