# Generated by Django 3.1.7 on 2021-03-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summons", "0008_remove_summon_intention_closing_decision"),
        ("decisions", "0002_auto_20210317_1057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="summon",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision",
                to="summons.summon",
            ),
        ),
    ]
