# Generated by Django 3.2.7 on 2022-03-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0002_decision_nuisance_detected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decision",
            name="nuisance_detected",
        ),
    ]
