# Generated by Django 3.1.7 on 2021-03-18 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("decisions", "0003_auto_20210317_1814"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decisiontype",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="decision",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="decision",
            name="sanction_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=100, null=True
            ),
        ),
    ]
