# Generated by Django 3.2.7 on 2022-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0003_remove_decision_nuisance_detected"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
