# Generated by Django 3.1.7 on 2021-06-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0007_auto_20210525_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="sanction_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
