# Generated by Django 3.1.7 on 2021-06-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0008_decision_sanction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="sanction_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
