# Generated by Django 3.1.5 on 2021-02-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0039_auto_20210204_1438"),
        ("camunda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericcompletedtask",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="cases.casestate",
            ),
        ),
    ]
