# Generated by Django 3.1.5 on 2021-02-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0002_auto_20210215_2059"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericcompletedtask",
            name="variables",
            field=models.JSONField(null=True),
        ),
    ]
