# Generated by Django 3.1.7 on 2021-04-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0003_genericcompletedtask_variables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericcompletedtask",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cases.case"
            ),
        ),
        migrations.AlterField(
            model_name="genericcompletedtask",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cases.casestate",
            ),
        ),
    ]
