# Generated by Django 3.1.7 on 2021-03-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0003_genericcompletedtask_variables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericcompletedtask",
            name="state",
        ),
    ]
