# Generated by Django 3.1.7 on 2021-04-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0004_auto_20210402_1103"),
        ("camunda", "0004_remove_genericcompletedtask_state"),
    ]

    operations = []
