# Generated by Django 3.1.8 on 2021-04-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0006_camundaprocess"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camundaprocess",
            old_name="camunda_process_name",
            new_name="camunda_message_name",
        ),
    ]
