# Generated by Django 3.1.8 on 2021-05-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0007_auto_20210415_1112"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camundaprocess",
            options={"ordering": ["name"]},
        ),
    ]
