# Generated by Django 3.1.8 on 2021-06-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0010_auto_20210520_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="camundaprocess",
            name="to_directing_proccess",
            field=models.BooleanField(default=False),
        ),
    ]
