# Generated by Django 3.2.5 on 2021-07-16 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    def map_processes_to_theme(apps, schema_editor):
        CaseTheme = apps.get_model("cases", "CaseTheme")
        CamundaProcess = apps.get_model("camunda", "CamundaProcess")

        case_theme = CaseTheme.objects.all().first()
        for process in CamundaProcess.objects.all():
            process.theme = case_theme
            process.save()

    dependencies = [
        ("cases", "0077_auto_20210716_1209"),
        ("camunda", "0011_camundaprocess_to_directing_proccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="camundaprocess",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cases.casetheme",
            ),
        ),
        migrations.RunPython(map_processes_to_theme, migrations.RunPython.noop),
    ]
