# Generated by Django 3.2.5 on 2021-07-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0077_auto_20210716_1209"),
        ("camunda", "0012_camundaprocess_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camundaprocess",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cases.casetheme"
            ),
        ),
    ]
