# Generated by Django 3.2.7 on 2021-11-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "camunda",
            "0014_rename_camunda_task_id_genericcompletedtask_case_user_task_id",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericcompletedtask",
            name="author",
        ),
        migrations.RemoveField(
            model_name="genericcompletedtask",
            name="case",
        ),
        migrations.DeleteModel(
            name="CamundaProcess",
        ),
        migrations.DeleteModel(
            name="GenericCompletedTask",
        ),
    ]
