# Generated by Django 3.2.7 on 2022-01-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debriefing",
            name="violation",
            field=models.CharField(
                choices=[
                    ("NO", "No"),
                    ("YES", "Yes"),
                    ("ADDITIONAL_RESEARCH_REQUIRED", "Additional research required"),
                    ("ADDITIONAL_VISIT_REQUIRED", "Nieuw huisbezoek nodig"),
                    (
                        "ADDITIONAL_VISIT_WITH_AUTHORIZATION",
                        "Nieuw huisbezoek inclusief machtingaanvraag",
                    ),
                    ("SEND_TO_OTHER_THEME", "Naar ander team"),
                    ("LIKELY_INHABITED", "Vermoeden bewoning"),
                ],
                default="NO",
                max_length=255,
            ),
        ),
    ]
