# Generated by Django 3.2.7 on 2022-03-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0002_alter_debriefing_violation"),
    ]

    operations = [
        migrations.AddField(
            model_name="debriefing",
            name="nuisance_detected",
            field=models.BooleanField(default=False),
        ),
    ]
