# Generated by Django 3.1.2 on 2020-10-21 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0017_auto_20201015_0852"),
        ("debriefings", "0002_auto_20201021_0508"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debriefing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("hit", models.BooleanField()),
                ("feedback", models.CharField(max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="debriefings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="debriefings",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Debrief",
        ),
    ]
