# Generated by Django 3.1.2 on 2020-10-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0003_auto_20201021_0750"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debriefing",
            old_name="hit",
            new_name="violation",
        ),
    ]
