# Generated by Django 3.2.13 on 2023-05-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0003_debriefing_nuisance_detected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debriefing",
            name="violation",
            field=models.CharField(
                choices=[
                    ("NO", "Geen overtreding"),
                    ("YES", "Overtreding"),
                    ("ADDITIONAL_RESEARCH_REQUIRED", "Nader intern onderzoek nodig"),
                    ("ADDITIONAL_VISIT_REQUIRED", "Aanvullend bezoek nodig"),
                    ("ADDITIONAL_VISIT_WITH_AUTHORIZATION", "Machtiging benodigd"),
                    ("SEND_TO_OTHER_THEME", "Naar ander thema"),
                    ("LIKELY_INHABITED", "Vermoeden bewoning/leegstand"),
                ],
                default="NO",
                max_length=255,
            ),
        ),
    ]
