# Generated by Django 3.1.2 on 2020-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0004_auto_20201022_0253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debriefing",
            name="violation",
            field=models.CharField(
                choices=[
                    ("NO", "No"),
                    ("YES", "Yes"),
                    ("ARQ", "Additional research required"),
                ],
                default="NO",
                max_length=3,
            ),
        ),
    ]
