# Generated by Django 3.2.13 on 2024-02-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0004_added_tag_to_case_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debriefing",
            name="violation",
            field=models.CharField(
                choices=[
                    ("NO", "Geen overtreding"),
                    ("YES", "Overtreding"),
                    ("ADDITIONAL_RESEARCH_REQUIRED", "Nader intern onderzoek nodig"),
                    ("ADDITIONAL_VISIT_REQUIRED", "Aanvullend bezoek nodig"),
                    ("ADDITIONAL_VISIT_WITH_AUTHORIZATION", "Machtiging benodigd"),
                    ("SEND_TO_OTHER_THEME", "Naar ander thema"),
                    ("LIKELY_INHABITED", "Vermoeden bewoning/leegstand"),
                    ("SERVICE_COSTS", "Narekenen onredelijke servicekosten"),
                    ("SCHEDULE_CONVERSATION", "Inplannen gesprek"),
                    ("ADVICE_OTHER_DISCIPLINE", "Afwachten advies andere discipline"),
                    ("REQUEST_DOCUMENTS", "Opvragen stukken"),
                    ("SEND_TO_WOON", "Doorsturen naar !Woon"),
                    (
                        "SEND_TO_ANOTHER_EXTERNAL_PARTY",
                        "Doorsturen naar andere externe partij",
                    ),
                ],
                default="NO",
                max_length=255,
            ),
        ),
    ]
