# Generated by Django 4.2.16 on 2025-04-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0026_update_sequence_pk"),
        ("debriefings", "0005_alter_debriefing_violation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViolationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "theme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violation_types",
                        to="cases.casetheme",
                    ),
                ),
            ],
        ),
    ]
