# Generated by Django 3.1.3 on 2020-11-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0006_auto_20201027_1018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debriefing",
            name="violation",
            field=models.CharField(
                choices=[
                    ("NO", "No"),
                    ("YES", "Yes"),
                    ("ADDITIONAL_RESEARCH_REQUIRED", "Additional research required"),
                    ("ADDITIONAL_VISIT_REQUIRED", "Nieuw huisbezoek nodig"),
                ],
                default="NO",
                max_length=28,
            ),
        ),
    ]
