# Generated by Django 4.2.16 on 2025-05-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0006_violationtype"),
    ]
    operations = [
        migrations.RenameField(
            model_name="debriefing",
            old_name="violation",
            new_name="violation_old",
        ),
        migrations.AddField(
            model_name="debriefing",
            name="violation",
            field=models.ForeignKey(
                to="debriefings.ViolationType",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debriefings",
            ),
        ),
    ]
