# Generated by Django 4.2.16 on 2025-05-07 07:49
from django.db import migrations


def migrate_violation_strings_to_foreign_keys(apps, schema_editor):
    Debriefing = apps.get_model("debriefings", "Debriefing")
    ViolationType = apps.get_model("debriefings", "ViolationType")

    for debriefing in Debriefing.objects.all():
        if not debriefing.violation_old:
            continue
        vt = ViolationType.objects.get(
            value=debriefing.violation_old, theme_id=debriefing.case.theme_id
        )
        debriefing.violation_id = vt.id
        debriefing.save(update_fields=["violation"])


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0007_debriefing_violation_old_alter_debriefing_violation"),
    ]

    operations = [
        migrations.RunPython(migrate_violation_strings_to_foreign_keys),
    ]
