# Generated by Django 4.2.16 on 2025-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0008_move_old_violation_to_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debriefing",
            name="violation_old",
            field=models.CharField(default="NO", max_length=255),
        ),
    ]
