# Generated by Django 3.1.8 on 2021-06-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0013_auto_20210608_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debriefing",
            name="feedback",
            field=models.TextField(),
        ),
    ]
