# Generated by Django 3.2.7 on 2021-10-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("debriefings", "0014_auto_20210617_1413"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debriefing",
            old_name="camunda_task_id",
            new_name="case_user_task_id",
        ),
    ]
