image:
  registry: 127.0.0.1:5001
  imagePullPolicy: Always

host: zaken-b.local

secrets:
  certificate:
    enabled: false
configMaps:
  env-vars:
    data:
      DATABASE_NAME: zaken
      DATABASE_HOST: psql-postgresql
      DATABASE_USER: salmagundi
      DATABASE_PASSWORD: insecure
      ENVIRONMENT: development
      DJANGO_SECRET_KEY: local
      UWSGI_HTTP: 0.0.0.0:8000
      UWSGI_STATIC_MAP: /static=/static
      SENTRY_DSN: https://foo@foo.data.amsterdam.nl/0
      LOCAL_DEVELOPMENT_AUTHENTICATION: "True"
      SECRET_KEY_TOP_ZAKEN: SECRET_KEY_TOP_ZAKEN
      SECRET_KEY_TON_ZAKEN: SECRET_KEY_TON_ZAKEN
      BELASTING_API_URL: https://api-acc.belastingen.centric.eu/bel/inn/afne/vora/v1/vorderingenidentificatienummer/
      BAG_API_SEARCH_URL: https://api.data.amsterdam.nl/atlas/search/adres/
      BAG_API_NUMMERAANDUIDING_SEARCH_URL: https://api.data.amsterdam.nl/v1/bag/nummeraanduidingen/
      DECOS_JOIN_USERNAME: ZakenTop
      DECOS_JOIN_PASSWORD: insecure
      REDIS: default:insecure@redis-master:6379
      DEFAULT_THEME: Vakantieverhuur
      DEFAULT_REASON: SIA melding
      VAKANTIEVERHUUR_TOERISTISCHE_VERHUUR_API_URL: https://api.acceptatie.toeristischeverhuur.nl/api/
      VAKANTIEVERHUUR_TOERISTISCHE_VERHUUR_API_ACCESS_TOKEN: SECRET_ACCESS_TOKEN
      VAKANTIEVERHUUR_TOERISTISCHE_VERHUUR_API_HEALTH_CHECK_BAG_ID: "0503100000000209"
      VAKANTIEVERHUUR_REGISTRATIE_API_URL: https://acceptatie.toeristischeverhuur.nl/ext/api/Registrations/
      VAKANTIEVERHUUR_REGISTRATIE_API_ACCESS_TOKEN: SECRET_ACCESS_TOKEN
      VAKANTIEVERHUUR_REGISTRATIE_API_HEALTH_CHECK_BSN: "999999990"
      VAKANTIEVERHUUR_REGISTRATIE_API_HEALTH_CHECK_BAG_ID: "0503100000000209"
      VAKANTIEVERHUUR_REGISTRATIE_API_HEALTH_CHECK_REGISTRATION_NUMBER: "05034542BC484F3891BB"
      ZAKEN_CONTAINER_HOST: http://zaak-gateway:8000
      DEFAULT_SCHEDULE_ACTIONS: Huisbezoek,Hercontrole
      DEFAULT_SCHEDULE_WEEK_SEGMENTS: Doordeweeks,Weekend
      DEFAULT_SCHEDULE_DAY_SEGMENTS: "Overdag,'s Avonds"
      DEFAULT_SCHEDULE_HIGH_PRIORITY: Hoog
      DEFAULT_SCHEDULE_NORMAL_PRIORITY: Normaal
      OPENZAAK_ENABLED: "True"
      OPENZAAK_CATALOGI_URL: http://172.17.0.1:8000/catalogi/api/v1/catalogussen/c135a500-beac-4774-bc0d-b582630e605d
      OPENZAAK_DEFAULT_INFORMATIEOBJECTTYPE: http://172.17.0.1:8000/catalogi/api/v1/informatieobjecttypen/b96d14b0-03ad-421a-bc7c-b501652a04b2
      HOST: http://172.17.0.1:8080
      USE_DECOS_MOCK_DATA: "False"
      SESSION_COOKIE_AGE: "25200"
      AXES_ENABLED: "False"

deployments:
  zaken-backend:
    configMaps:
      - env-vars

  zaken-celery-worker:
    configMaps:
      - env-vars

  zaken-celery-beat:
    configMaps:
      - env-vars

services:
  zaken-backend:
    selector:
      component: zaken-backend
    ports:
      - port: 8080
        targetPort: 8000

ingress:
  zaken-backend-internal:
    className: nginx

jobs:
  certificate-init:
    enabled: false