# Generated by Django 3.2.7 on 2021-11-16 09:57
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
    # operations = [
    #     migrations.CreateModel(
    #         name="WorkflowOption",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             ("name", models.CharField(max_length=255)),
    #             ("message_name", models.CharField(max_length=255)),
    #             ("to_directing_proccess", models.BooleanField(default=False)),
    #             (
    #                 "theme",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.CASCADE,
    #                     related_name="workflow_options",
    #                     to="cases.casetheme",
    #                 ),
    #             ),
    #         ],
    #         options={
    #             "ordering": ["name"],
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name="GenericCompletedTask",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             ("case_user_task_id", models.CharField(default="-1", max_length=255)),
    #             ("date_added", models.DateTimeField(auto_now_add=True)),
    #             ("description", models.TextField()),
    #             ("variables", models.JSONField(null=True)),
    #             (
    #                 "author",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.PROTECT,
    #                     related_name="generic_completed_tasks",
    #                     to=settings.AUTH_USER_MODEL,
    #                 ),
    #             ),
    #             (
    #                 "case",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.CASCADE,
    #                     related_name="generic_completed_tasks",
    #                     to="cases.case",
    #                 ),
    #             ),
    #         ],
    #         options={
    #             "abstract": False,
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name="CaseWorkflow",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             ("main_workflow", models.BooleanField(default=False)),
    #             (
    #                 "workflow_type",
    #                 models.CharField(
    #                     choices=[
    #                         ("main_workflow", "main_workflow"),
    #                         ("sub_workflow", "sub_workflow"),
    #                         ("debrief", "debrief"),
    #                         ("closing_procedure", "closing_procedure"),
    #                         ("director", "director"),
    #                         ("visit", "visit"),
    #                         ("summon", "summon"),
    #                         ("decision", "decision"),
    #                         ("renounce_decision", "renounce_decision"),
    #                         ("close_case", "close_case"),
    #                     ],
    #                     default="director",
    #                     max_length=100,
    #                 ),
    #             ),
    #             ("workflow_version", models.CharField(max_length=100)),
    #             (
    #                 "workflow_theme_name",
    #                 models.CharField(blank=True, max_length=100, null=True),
    #             ),
    #             (
    #                 "workflow_message_name",
    #                 models.CharField(blank=True, max_length=100, null=True),
    #             ),
    #             ("created", models.DateTimeField(auto_now_add=True)),
    #             ("serialized_workflow_state", models.JSONField(null=True)),
    #             ("data", models.JSONField(null=True)),
    #             ("completed", models.BooleanField(default=False)),
    #             (
    #                 "case",
    #                 models.ForeignKey(
    #                     blank=True,
    #                     null=True,
    #                     on_delete=django.db.models.deletion.CASCADE,
    #                     related_name="workflows",
    #                     to="cases.case",
    #                 ),
    #             ),
    #             (
    #                 "parent_workflow",
    #                 models.ForeignKey(
    #                     blank=True,
    #                     null=True,
    #                     on_delete=django.db.models.deletion.CASCADE,
    #                     related_name="child_workflows",
    #                     to="workflow.caseworkflow",
    #                 ),
    #             ),
    #         ],
    #         options={
    #             "ordering": ["-id"],
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name="CaseUserTask",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             ("completed", models.BooleanField(default=False)),
    #             ("task_id", models.UUIDField(unique=True)),
    #             ("task_name", models.CharField(max_length=255)),
    #             ("name", models.CharField(max_length=255)),
    #             ("form", models.JSONField(blank=True, default=list, null=True)),
    #             (
    #                 "roles",
    #                 django.contrib.postgres.fields.ArrayField(
    #                     base_field=models.CharField(max_length=255),
    #                     blank=True,
    #                     default=list,
    #                     null=True,
    #                     size=None,
    #                 ),
    #             ),
    #             ("due_date", models.DateTimeField()),
    #             ("created", models.DateTimeField(auto_now_add=True)),
    #             ("updated", models.DateTimeField(auto_now=True)),
    #             (
    #                 "case",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.CASCADE,
    #                     related_name="tasks",
    #                     to="cases.case",
    #                 ),
    #             ),
    #             (
    #                 "owner",
    #                 models.ForeignKey(
    #                     blank=True,
    #                     null=True,
    #                     on_delete=django.db.models.deletion.PROTECT,
    #                     to=settings.AUTH_USER_MODEL,
    #                 ),
    #             ),
    #             (
    #                 "workflow",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.CASCADE,
    #                     related_name="tasks",
    #                     to="workflow.caseworkflow",
    #                 ),
    #             ),
    #         ],
    #     ),
    # ]
