# Generated by Django 3.2.7 on 2021-12-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20211213_1712"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="case_state_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="cases.casestatetype",
            ),
        ),
    ]
