# Generated by Django 3.2.5 on 2021-08-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_auto_20210829_1822"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("task_name", "workflow")},
        ),
    ]
