# Generated by Django 3.2.7 on 2022-01-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_alter_caseworkflow_workflow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("main_workflow", "main_workflow"),
                    ("sub_workflow", "sub_workflow"),
                    ("debrief", "debrief"),
                    ("closing_procedure", "closing_procedure"),
                    ("director", "director"),
                    ("visit", "visit"),
                    ("summon", "summon"),
                    ("decision", "decision"),
                    ("renounce_decision", "renounce_decision"),
                    ("close_case", "close_case"),
                    ("digital_surveillance", "digital_surveillance"),
                    ("housing_corporation", "housing_corporation"),
                    ("unoccupied", "unoccupied"),
                ],
                default="director",
                max_length=100,
            ),
        ),
    ]
