# Generated by Django 3.2.5 on 2021-08-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_alter_task_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="task",
            name="task_name_id",
            field=models.CharField(default="task_id", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("task_name_id", "workflow")},
        ),
    ]
