# Generated by Django 3.2.5 on 2021-08-31 07:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0005_auto_20210830_2023"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
