# Generated by Django 3.2.7 on 2022-03-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_alter_caseworkflow_workflow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericcompletedtask",
            name="task_name",
            field=models.CharField(default="user_task", max_length=255),
            preserve_default=False,
        ),
    ]
