# Generated by Django 3.2.5 on 2021-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_task_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="workflow_spec",
            field=models.CharField(default="VAKANTIEVERHUUR_WORKFLOW", max_length=100),
        ),
    ]
