# Generated by Django 3.2.5 on 2021-09-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_workflow_workflow_spec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="workflow_spec",
            field=models.CharField(
                choices=[["VAKANTIEVERHUUR_WORKFLOW", "VAKANTIEVERHUUR_WORKFLOW"]],
                default="VAKANTIEVERHUUR_WORKFLOW",
                max_length=100,
            ),
        ),
    ]
