# Generated by Django 3.2.13 on 2024-02-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_workflowoption_enabled_on_case_closed"),
    ]

    operations = []
