# Generated by Django 3.2.5 on 2021-09-06 18:46

import uuid

from django.db import migrations, models


def create_uuid(apps, schema_editor):
    Task = apps.get_model("workflow", "Task")
    for task in Task.objects.all():
        task.task_id = uuid.uuid4()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_alter_workflow_workflow_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.UUIDField(
                unique=True,
                default=uuid.uuid4,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
    ]
