# Generated by Django 3.2.5 on 2021-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0010_remove_task_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="form",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
