# Generated by Django 5.2.5 on 2025-10-08 10:06

from django.db import migrations, models


def set_spiff_workflow_version_default(apps, schema_editor):
    CaseWorkflow = apps.get_model("workflow", "CaseWorkflow")
    CaseWorkflow.objects.update(spiff_workflow_version="1.1.0")


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0010_update_sequence_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="spiff_serializer_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="spiff_workflow_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(
            set_spiff_workflow_version_default, migrations.RunPython.noop
        ),
    ]
