# Generated by Django 5.2.7 on 2025-10-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0011_caseworkflow_spiff_serializer_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="data_migration_backup",
            field=models.JSONField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="serialized_workflow_state_migration_backup",
            field=models.JSONField(null=True, blank=True),
        ),
    ]
