# Generated by Django 3.2.5 on 2021-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_task_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="workflow_spec",
            field=models.CharField(
                choices=[
                    ["VAKANTIEVERHUUR_WORKFLOW", "VAKANTIEVERHUUR_WORKFLOW"],
                    ["SIGNAL_WORKFLOW", "SIGNAL_WORKFLOW"],
                ],
                default={
                    "main_proccess": "aza_wonen_local_vakantieverhuur_regie",
                    "proccess_files": [
                        "aza_wonen_global_afronden_zaak.bpmn",
                        "aza_wonen_global_voornemen_afzien.bpmn",
                        "aza_wonen_global_decision.bpmn",
                        "aza_wonen_global_summon.bpmn",
                        "aza_wonen_global_visit.bpmn",
                        "aza_wonen_local_vakantieverhuur_regie.bpmn",
                    ],
                },
                max_length=100,
            ),
        ),
    ]
