# Generated by Django 5.2.8 on 2025-12-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_caseworkflow_data_migration_backup_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("main_workflow", "main_workflow"),
                    ("sub_workflow", "sub_workflow"),
                    ("debrief", "debrief"),
                    ("closing_procedure", "closing_procedure"),
                    ("director", "director"),
                    ("visit", "visit"),
                    ("summon", "summon"),
                    ("decision", "decision"),
                    ("omzettingsvergunning", "omzettingsvergunning"),
                    ("renounce_decision", "renounce_decision"),
                    ("close_case", "close_case"),
                    ("digital_surveillance", "digital_surveillance"),
                    ("housing_corporation", "housing_corporation"),
                    ("unoccupied", "unoccupied"),
                    ("citizen_report_feedback", "citizen_report_feedback"),
                ],
                default="director",
                max_length=100,
            ),
        ),
    ]
