# Generated by Django 3.2.5 on 2021-09-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0013_alter_workflow_workflow_spec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="workflow_spec",
            field=models.CharField(
                choices=[
                    ["VAKANTIEVERHUUR_WORKFLOW", "VAKANTIEVERHUUR_WORKFLOW"],
                    ["SIGNAL_WORKFLOW", "SIGNAL_WORKFLOW"],
                ],
                default="VAKANTIEVERHUUR_WORKFLOW",
                max_length=100,
            ),
        ),
    ]
