# Generated by Django 3.2.5 on 2021-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0014_alter_workflow_workflow_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
