# Generated by Django 3.2.5 on 2021-09-17 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0015_workflow_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflow",
            name="main_workflow",
            field=models.BooleanField(default=False),
        ),
    ]
