# Generated by Django 3.2.5 on 2021-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0016_auto_20210917_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("main_workflow", "main_workflow"),
                    ("sub_workflow", "sub_workflow"),
                ],
                default="main_workflow",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="workflow_version",
            field=models.CharField(
                choices=[["0.1.0", "0.1.0"]], default="0.1.0", max_length=100
            ),
        ),
    ]
