# Generated by Django 3.2.7 on 2021-09-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0020_alter_workflow_workflow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="workflow_theme_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
