# Generated by Django 3.2.7 on 2021-09-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0022_auto_20210927_1801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("main_workflow", "main_workflow"),
                    ("sub_workflow", "sub_workflow"),
                    ("director", "director"),
                    ("visit", "visit"),
                    ("summon", "summon"),
                    ("decision", "decision"),
                    ("renounce_decision", "renounce_decision"),
                    ("close_case", "close_case"),
                ],
                default="main_workflow",
                max_length=100,
            ),
        ),
    ]
