# Generated by Django 3.2.7 on 2021-09-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0084_alter_casestate_workflow"),
        ("visits", "0009_visit_task"),
        ("workflow", "0023_alter_workflow_workflow_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="CaseUserTask",
        ),
    ]
