# Generated by Django 3.2.7 on 2021-09-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0084_alter_casestate_workflow"),
        ("workflow", "0024_rename_task_caseusertask"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Workflow",
            new_name="CaseWorkflow",
        ),
    ]
