# Generated by Django 3.2.7 on 2021-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0025_rename_workflow_caseworkflow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caseusertask",
            old_name="task_name_id",
            new_name="task_name",
        ),
    ]
