# Generated by Django 3.2.7 on 2021-10-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0026_rename_task_name_id_caseusertask_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="parent_workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_workflows",
                to="workflow.caseworkflow",
            ),
        ),
    ]
