# Generated by Django 3.2.7 on 2021-10-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0028_caseworkflow_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseusertask",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
