# Generated by Django 3.2.7 on 2021-10-11 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0029_caseusertask_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caseworkflow",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="caseusertask",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
