# Generated by Django 3.2.7 on 2021-10-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0030_auto_20211011_1730"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="workflow_message_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
