# Generated by Django 3.2.7 on 2021-10-14 08:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0030_auto_20211011_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseusertask",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 10, 14, 10, 26, 49, 997948)
            ),
            preserve_default=False,
        ),
    ]
