# Generated by Django 3.2.7 on 2021-10-14 09:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0031_caseworkflow_workflow_message_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseusertask",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 10, 14, 11, 36, 24, 877937)
            ),
            preserve_default=False,
        ),
    ]
