# Generated by Django 3.2.7 on 2021-10-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0031_caseworkflow_workflow_message_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseworkflow",
            name="workflow_type",
            field=models.CharField(
                choices=[
                    ("main_workflow", "main_workflow"),
                    ("sub_workflow", "sub_workflow"),
                    ("debrief", "debrief"),
                    ("director", "director"),
                    ("visit", "visit"),
                    ("summon", "summon"),
                    ("decision", "decision"),
                    ("renounce_decision", "renounce_decision"),
                    ("close_case", "close_case"),
                ],
                default="director",
                max_length=100,
            ),
        ),
    ]
