# Generated by Django 3.2.7 on 2021-10-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0032_alter_caseusertask_due_date"),
        ("workflow", "0032_alter_caseworkflow_workflow_type"),
    ]

    operations = []
