# Generated by Django 3.2.7 on 2021-10-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0087_auto_20211013_1450"),
        ("workflow", "0033_merge_20211019_1156"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("message_name", models.CharField(max_length=255)),
                ("to_directing_proccess", models.BooleanField(default=False)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_options",
                        to="cases.casetheme",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
