# Generated by Django 3.2.7 on 2021-10-19 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0087_auto_20211013_1450"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workflow", "0035_auto_20211019_1509"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericCompletedTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_user_task_id", models.CharField(default="-1", max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("variables", models.JSONField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generic_completed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generic_completed_tasks",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
