# Generated by Django 3.2.7 on 2021-10-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0036_genericcompletedtask"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO workflow_genericcompletedtask (
                id,
                date_added,
                description,
                author_id,
                case_id,
                variables,
                case_user_task_id
            )
            SELECT
                id,
                date_added,
                description,
                author_id,
                case_id,
                variables,
                case_user_task_id
            FROM
                camunda_genericcompletedtask;
        """,
            reverse_sql="""
            INSERT INTO camunda_genericcompletedtask (
                id,
                date_added,
                description,
                author_id,
                case_id,
                variables,
                case_user_task_id
            )
            SELECT
                id,
                date_added,
                description,
                author_id,
                case_id,
                variables,
                case_user_task_id
            FROM
                workflow_genericcompletedtask;
        """,
        ),
    ]
