# Generated by Django 3.2.7 on 2021-10-19 13:44

from django.db import migrations


def change_case_event_content_type(apps, schema_editor):
    CaseEvent = apps.get_model("events", "CaseEvent")
    ContentType = apps.get_model(app_label="contenttypes", model_name="ContentType")

    old_generic_completed_task_contenttype = ContentType.objects.get(
        app_label="camunda", model="genericcompletedtask"
    )
    new_generic_completed_task_contenttype = ContentType.objects.get(
        app_label="workflow", model="genericcompletedtask"
    )

    case_events = CaseEvent.objects.filter(
        emitter_type_id=old_generic_completed_task_contenttype.id
    )
    case_events.update(emitter_type_id=new_generic_completed_task_contenttype.id)


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0036_genericcompletedtask"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO workflow_genericcompletedtask (
                id,
                date_added,
                description,
                author_id,
                case_id,
                variables,
                case_user_task_id
            )
            SELECT
                id,
                date_added,
                description,
                author_id,
                case_id,
                variables,
                case_user_task_id
            FROM
                camunda_genericcompletedtask;
        """
        ),
        migrations.RunPython(change_case_event_content_type),
    ]
