# Generated by Django 3.0.8 on 2020-07-13 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bag_id", models.CharField(max_length=255, unique=True)),
                (
                    "street_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_number",
                    models.IntegerField(blank=True, max_length=8, null=True),
                ),
                (
                    "suffix_letter",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("suffix", models.CharField(blank=True, max_length=4, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=6, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_date", models.DateField(auto_now=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="cases.Address",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="cases.Project",
                    ),
                ),
            ],
            options={"ordering": ["start_date"],},
        ),
    ]
