# Generated by Django 3.2.7 on 2021-11-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="camunda_ids",
        ),
        migrations.RemoveField(
            model_name="case",
            name="directing_process",
        ),
        migrations.DeleteModel(
            name="CaseProcessInstance",
        ),
    ]
