# Generated by Django 3.0.8 on 2020-07-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_auto_20200713_0918"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
