# Generated by Django 3.2.7 on 2021-12-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="casetheme",
            name="sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="casestatetype",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_types",
                to="cases.casetheme",
            ),
        ),
    ]
