# Generated by Django 3.0.8 on 2020-07-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_address_lat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="street_number",
            new_name="number",
        ),
    ]
