# Generated by Django 3.2.7 on 2021-12-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_auto_20211213_1430"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cases.casetheme",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="cases.Subject"
            ),
        ),
    ]
