# Generated by Django 3.0.8 on 2020-07-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20200713_1003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
