# Generated by Django 3.2.7 on 2022-01-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20211213_1712"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseproject",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
