# Generated by Django 3.2.7 on 2022-01-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_auto_20220118_1234"),
        ("cases", "0005_caseproject_active"),
    ]

    operations = []
