# Generated by Django 3.0.8 on 2020-07-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_auto_20200713_1005"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="CaseType",
        ),
        migrations.RenameField(
            model_name="case",
            old_name="project",
            new_name="case_type",
        ),
    ]
