# Generated by Django 3.2.7 on 2022-02-07 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_merge_0005_auto_20220118_1234_0005_caseproject_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="ton_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveBigIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
