# Generated by Django 3.2.7 on 2022-02-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_advertisements",
                to="cases.case",
            ),
        ),
    ]
