# Generated by Django 3.2.7 on 2022-03-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20220307_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='This field determines if the case is deleted in openzaak.'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_url',
            field=models.URLField(blank=True, help_text='This is the case that can be found in openzaak.', null=True),
        ),
        migrations.AddField(
            model_name='casestate',
            name='set_in_open_zaak',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='casestate',
            name='system_build',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='casestatetype',
            name='state_type_url',
            field=models.URLField(help_text='This is the state type that can be found in openzaak. This way all the state types can be linked within the systems.', null=True),
        ),
        migrations.AddField(
            model_name='casetheme',
            name='case_type_url',
            field=models.URLField(help_text='This is the case type that can be found in openzaak. This way all the case types can be linked within the systems.', null=True),
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_url', models.URLField()),
                ('document_content', models.URLField()),
                ('connected', models.BooleanField(blank=True, default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
