# Generated by Django 3.2.7 on 2022-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_auto_20220329_1608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestate",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
