# Generated by Django 3.2.7 on 2022-04-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_auto_20220404_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_enforcement_request",
            field=models.BooleanField(default=False),
        ),
    ]
