# Generated by Django 3.2.7 on 2022-04-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20220331_1353'),
        ('cases', '0011_case_is_enforcement_request'),
    ]

    operations = [
    ]
