# Generated by Django 3.2.7 on 2022-03-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_alter_casestate_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casetheme",
            name="case_state_types_top",
        ),
    ]
