# Generated by Django 3.2.7 on 2022-04-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_merge_20220407_1013"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casestatetype",
            name="state_type_url",
        ),
    ]
