# Generated by Django 3.2.13 on 2022-04-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_remove_casestatetype_state_type_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatetype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
