# Generated by Django 3.2.13 on 2022-05-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_alter_casestatetype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="case_document_connection_url",
            field=models.URLField(blank=True, default=False),
        ),
    ]
