# Generated by Django 3.1.2 on 2020-10-06 05:37

from django.db import migrations


class Migration(migrations.Migration):
    def connect_case_to_visit_via_itinerary_item(apps, schema_editor):
        CaseTimelineSubject = apps.get_model("cases", "CaseTimelineSubject")

        CaseTimelineSubject.objects.all().delete()

    dependencies = [
        ("cases", "0014_casetimelinesubject_case"),
    ]

    operations = [
        migrations.RunPython(
            connect_case_to_visit_via_itinerary_item, migrations.RunPython.noop
        ),
    ]
