# Generated by Django 3.2.13 on 2022-07-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0015_casedocument_case_document_connection_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casecloseresult",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="casestatetype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name"]},
        ),
        migrations.DeleteModel(
            name="CaseProcessInstance",
        ),
    ]
