# Generated by Django 3.1.2 on 2020-10-06 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0015_auto_20201006_0537"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetimelinesubject",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cases.case"
            ),
        ),
    ]
