# Generated by Django 3.1.2 on 2020-10-15 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0016_auto_20201006_0540"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStateType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name="State",
            new_name="LegacyState",
        ),
        migrations.RenameModel(
            old_name="StateType",
            new_name="LegacyStateType",
        ),
        migrations.CreateModel(
            name="CaseState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_date", models.DateField()),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.case"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cases.casestatetype",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="case_states",
                        related_query_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
