# Generated by Django 3.2.13 on 2022-07-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_auto_20220712_1100"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="directing_process",
        ),
    ]
