# Generated by Django 3.1.2 on 2020-10-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_auto_20201015_0852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetimelinesubject",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_timeline_subjects",
                to="cases.case",
            ),
        ),
    ]
