# Generated by Django 3.1.2 on 2020-10-28 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("cases", "0018_auto_20201022_0321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="addresses.address",
            ),
        ),
    ]
