# Generated by Django 3.2.13 on 2022-07-13 09:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_alter_advertisement_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="ton_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
