# Generated by Django 3.1.2 on 2020-10-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_auto_20201022_0321"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="case_type",
        ),
        migrations.DeleteModel(
            name="CaseType",
        ),
    ]
