# Generated by Django 3.1.2 on 2020-10-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_auto_20201027_0831"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpenZaakState",
        ),
        migrations.DeleteModel(
            name="OpenZaakStateType",
        ),
    ]
