# Generated by Django 3.2.13 on 2023-01-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_alter_case_ton_ids"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestate",
            options={"ordering": ["-last_updated"]},
        ),
        migrations.AddField(
            model_name="casestate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
