# Generated by Django 3.2.13 on 2023-01-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_alter_casestate_last_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={"ordering": ["-id"]},
        ),
    ]
