# Generated by Django 3.1.2 on 2020-10-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_auto_20201028_0612"),
        ("cases", "0020_auto_20201027_0846"),
    ]

    operations = []
