# Generated by Django 3.1.2 on 2020-10-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_merge_20201028_0616"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
