# Generated by Django 3.2.13 on 2023-05-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_added_tag_to_case_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="tag",
        ),
        migrations.AddField(
            model_name="case",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="cases.Tag"
            ),
        ),
    ]
