# Generated by Django 3.1.2 on 2020-10-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_delete_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casetimelinesubject",
            name="case",
        ),
        migrations.RemoveField(
            model_name="casetimelinethread",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="casetimelinethread",
            name="subject",
        ),
        migrations.DeleteModel(
            name="CaseTimelineReaction",
        ),
        migrations.DeleteModel(
            name="CaseTimelineSubject",
        ),
        migrations.DeleteModel(
            name="CaseTimelineThread",
        ),
    ]
