# Generated by Django 3.2.13 on 2024-02-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_add_multiple_tags"),
    ]

    operations = []
