# Generated by Django 3.1.3 on 2020-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_auto_20201030_0437"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatetype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
