# Generated by Django 3.1.3 on 2020-12-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_auto_20201119_1047"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_legacy_bwv",
            field=models.BooleanField(default=False),
        ),
    ]
