# Generated by Django 3.1.5 on 2021-01-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_case_is_legacy_bwv"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="camunda_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
