# Generated by Django 5.2.5 on 2025-08-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0026_update_sequence_pk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaseDocument",
        ),
    ]
