# Generated by Django 3.2.13 on 2024-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_update_sequence_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='consent_to_share_info',
            field=models.BooleanField(default=False, help_text='This field determines if the case can be shared with a third party (housing corporation).'),
        ),
    ]
