# Generated by Django 3.1.5 on 2021-01-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0028_case_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="case_reason",
            new_name="reason",
        ),
        migrations.RenameField(
            model_name="case",
            old_name="case_team",
            new_name="team",
        ),
    ]
