# Generated by Django 3.1.5 on 2021-01-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0029_auto_20210122_1415"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casereason",
            old_name="case_team",
            new_name="team",
        ),
    ]
