# Generated by Django 3.1.5 on 2021-01-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0030_auto_20210122_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereason",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_reasons",
                to="cases.caseteam",
            ),
        ),
    ]
