# Generated by Django 3.1.5 on 2021-01-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0031_auto_20210122_1419"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="text",
            new_name="description",
        ),
    ]
