# Generated by Django 3.1.5 on 2021-01-22 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    def update_cases(apps, schema_editor):
        CaseTeam = apps.get_model("cases", "CaseTeam")
        CaseReason = apps.get_model("cases", "CaseReason")

        team, _ = CaseTeam.objects.get_or_create(name=settings.DEFAULT_THEME)
        reason, _ = CaseReason.objects.get_or_create(
            name=settings.DEFAULT_REASON, team=team
        )

        Case = apps.get_model("cases", "Case")
        for case in Case.objects.all():
            case.team = team
            case.reason = reason
            case.save()

    dependencies = [
        ("cases", "0032_auto_20210122_1419"),
    ]

    operations = [
        migrations.RunPython(update_cases),
    ]
