# Generated by Django 3.1.5 on 2021-01-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0033_auto_20210122_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cases.casereason"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cases.caseteam"
            ),
        ),
    ]
