# Generated by Django 3.1.5 on 2021-01-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0035_auto_20210122_1532"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casereason",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="caseteam",
            options={"ordering": ["name"]},
        ),
    ]
