# Generated by Django 3.1.5 on 2021-01-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0037_case_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="created_by",
            new_name="author",
        ),
    ]
