# Generated by Django 3.1.5 on 2021-02-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0038_auto_20210126_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseteam",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
