# Generated by Django 3.1.5 on 2021-02-02 09:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    def create_uuid_for_cases(apps, schema_editor):
        Case = apps.get_model("cases", "Case")
        for case in Case.objects.all():
            temp_id = uuid.uuid4()
            case.temp_id = temp_id
            case.save()

    dependencies = [
        ("cases", "0038_auto_20210126_1136"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="identification",
        ),
        migrations.AddField(
            model_name="case",
            name="temp_id",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(
            create_uuid_for_cases, reverse_code=migrations.RunPython.noop
        ),
    ]
