# Generated by Django 3.1.6 on 2021-02-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0039_auto_20210204_1438"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casestate",
            old_name="state_date",
            new_name="start_date",
        ),
    ]
