# Generated by Django 3.1.5 on 2021-02-02 10:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0039_auto_20210202_1059"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="id",
        ),
        migrations.AlterField(
            model_name="case",
            name="temp_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
