# Generated by Django 3.1.6 on 2021-02-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0040_auto_20210222_2004"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestate",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
