# Generated by Django 3.1.5 on 2021-02-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0040_auto_20210202_1101"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="temp_id",
            new_name="id",
        ),
    ]
