# Generated by Django 3.1.6 on 2021-02-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0041_casestate_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestate",
            options={"ordering": ["start_date"]},
        ),
    ]
