# Generated by Django 3.1.7 on 2021-03-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0043_auto_20210315_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestatetype",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="cases.caseteam",
            ),
        ),
    ]
