# Generated by Django 3.1.7 on 2021-03-23 20:10

import apps.cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0044_casestatetype_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatetype",
            name="team",
            field=models.ForeignKey(
                default=apps.cases.models.CaseStateType.default_team,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_types",
                to="cases.caseteam",
            ),
        ),
    ]
