# Generated by Django 3.1.7 on 2021-03-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0045_auto_20210323_2110"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={"ordering": ["-start_date"]},
        ),
    ]
