# Generated by Django 3.1.8 on 2021-04-19 21:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0047_auto_20210419_1418"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="camunda_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
    ]
