# Generated by Django 3.1.8 on 2021-04-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0048_auto_20210419_2331"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="camunda_id",
            new_name="camunda_ids",
        ),
    ]
