# Generated by Django 3.1.8 on 2021-04-19 23:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0049_auto_20210419_2332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="camunda_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
