# Generated by Django 3.1.8 on 2021-05-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0051_citizenreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CitizenReport",
        ),
    ]
