# Generated by Django 3.1.8 on 2021-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0054_auto_20210519_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizenreport",
            name="camunda_task_id",
            field=models.CharField(default="-1", max_length=255),
        ),
    ]
