# Generated by Django 3.1.8 on 2021-05-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0055_auto_20210520_1201"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="team",
            new_name="theme",
        ),
        migrations.RenameField(
            model_name="casereason",
            old_name="team",
            new_name="theme",
        ),
        migrations.RenameField(
            model_name="casestatetype",
            old_name="team",
            new_name="theme",
        ),
    ]
