# Generated by Django 3.1.8 on 2021-05-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0010_auto_20210525_1424"),
        ("summons", "0012_auto_20210525_1424"),
        ("decisions", "0007_auto_20210525_1424"),
        ("cases", "0056_auto_20210525_1424"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaseTeam",
            new_name="CaseTheme",
        ),
    ]
