# Generated by Django 3.1.8 on 2021-05-25 17:47

import apps.cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0057_auto_20210525_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatetype",
            name="theme",
            field=models.ForeignKey(
                default=apps.cases.models.CaseStateType.default_theme,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_types",
                to="cases.casetheme",
            ),
        ),
    ]
