# Generated by Django 3.1.8 on 2021-05-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0057_caseprocessinstance"),
        ("cases", "0058_auto_20210525_1947"),
    ]

    operations = []
