# Generated by Django 3.1.8 on 2021-05-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0059_merge_20210526_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestate",
            name="case_process_id",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
