# Generated by Django 3.1.8 on 2021-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0060_casestate_case_process_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="legacy_bwv_case_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
