# Generated by Django 3.1.8 on 2021-06-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0061_case_legacy_bwv_case_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="citizenreport",
            old_name="description",
            new_name="description_citizenreport",
        ),
    ]
