# Generated by Django 3.1.8 on 2021-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0062_auto_20210601_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetheme",
            name="case_state_types_top",
            field=models.ManyToManyField(blank=True, to="cases.CaseStateType"),
        ),
    ]
