# Generated by Django 3.1.8 on 2021-06-06 22:56

from django.db import migrations


class Migration(migrations.Migration):
    def add_case_close_reason(apps, schema_editor):
        CaseCloseReason = apps.get_model("cases", "CaseCloseReason")

        CaseCloseReason.objects.get_or_create(name="Niemand thuis", result=False)
        CaseCloseReason.objects.get_or_create(name="Geen woonfraude", result=False)
        CaseCloseReason.objects.get_or_create(
            name="Doorzetten naar ander team", result=False
        )
        CaseCloseReason.objects.get_or_create(name="Onvoldoende bewijs", result=False)
        CaseCloseReason.objects.get_or_create(
            name="Anders, vermeld in toelichting", result=False
        )

        CaseCloseReason.objects.get_or_create(name="Regulier bewoond", result=True)
        CaseCloseReason.objects.get_or_create(name="Regulier verhuurd", result=True)
        CaseCloseReason.objects.get_or_create(name="Gelegaliseerd", result=True)

    dependencies = [
        ("cases", "0064_caseclose_caseclosereason"),
    ]

    operations = [
        migrations.RunPython(add_case_close_reason, migrations.RunPython.noop),
    ]
