# Generated by Django 3.1.8 on 2021-06-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0065_auto_20210607_0056"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseclosereason",
            name="case_theme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="cases.casetheme",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CaseCloseResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "case_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cases.casetheme",
                    ),
                ),
            ],
        ),
    ]
