# Generated by Django 3.1.8 on 2021-06-08 07:13

from django.db import migrations


class Migration(migrations.Migration):
    def delete_all_current_reasons(apps, schema_editor):
        CaseCloseReason = apps.get_model("cases", "CaseCloseReason")

        CaseCloseReason.objects.all().delete()

    def create_new_reasons_and_results(apps, schema_editor):
        CaseTheme = apps.get_model("cases", "CaseTheme")
        CaseCloseReason = apps.get_model("cases", "CaseCloseReason")
        CaseCloseResult = apps.get_model("cases", "CaseCloseResult")

        case_theme = CaseTheme.objects.get(name="Vakantieverhuur")

        CaseCloseReason.objects.get_or_create(
            name="Geen aanleiding adres opnieuw te bezoeken",
            result=False,
            case_theme=case_theme,
        )
        CaseCloseReason.objects.get_or_create(
            name="Doorgezet naar ander team", result=False, case_theme=case_theme
        )
        CaseCloseReason.objects.get_or_create(
            name="Geen woonfraude", result=False, case_theme=case_theme
        )
        CaseCloseReason.objects.get_or_create(
            name="Onvoldoende bewijs", result=False, case_theme=case_theme
        )
        CaseCloseReason.objects.get_or_create(
            name="Resultaat na hercontrole", result=True, case_theme=case_theme
        )
        CaseCloseReason.objects.get_or_create(
            name="Anders, vermeld in toelichting", result=False, case_theme=case_theme
        )

        CaseCloseResult.objects.get_or_create(
            name="Regulier bewoond", case_theme=case_theme
        )
        CaseCloseResult.objects.get_or_create(
            name="Regulier verhuurd", case_theme=case_theme
        )
        CaseCloseResult.objects.get_or_create(
            name="Gelegaliseerd", case_theme=case_theme
        )

    dependencies = [
        ("cases", "0066_auto_20210608_0903"),
    ]

    operations = [
        migrations.RunPython(delete_all_current_reasons, migrations.RunPython.noop),
        migrations.RunPython(create_new_reasons_and_results, migrations.RunPython.noop),
    ]
