# Generated by Django 3.1.7 on 2021-06-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0068_caseclose_result"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caseclose",
            old_name="explanation",
            new_name="description",
        ),
    ]
