# Generated by Django 3.1.7 on 2021-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0069_auto_20210614_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseclose",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
