# Generated by Django 3.1.8 on 2021-06-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0071_caseclose_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseclose",
            name="camunda_task_id",
            field=models.CharField(default="-1", max_length=255),
        ),
    ]
