# Generated by Django 3.1.8 on 2021-06-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0072_caseclose_camunda_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cases.casetheme",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cases.caseproject",
            ),
        ),
    ]
