# Generated by Django 3.1.8 on 2021-07-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0070_case_directing_process"),
        ("cases", "0072_caseclose_camunda_task_id"),
    ]

    operations = []
