# Generated by Django 3.1.8 on 2021-07-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0073_merge_20210701_1104"),
        ("cases", "0073_auto_20210630_1506"),
    ]

    operations = []
