# Generated by Django 3.1.8 on 2021-07-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0075_auto_20210712_1132"),
        ("cases", "0074_citizenreport_reporter_email"),
    ]

    operations = []
