# Generated by Django 3.2.5 on 2021-07-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0076_merge_20210714_0913"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caseclosereason",
            options={"ordering": ["case_theme", "name"]},
        ),
        migrations.AlterModelOptions(
            name="caseproject",
            options={"ordering": ["theme", "name"]},
        ),
    ]
