# Generated by Django 3.2.5 on 2021-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0077_auto_20210716_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatetype",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="casestatetype",
            unique_together={("name", "theme")},
        ),
    ]
