# Generated by Django 3.2.5 on 2021-08-17 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0079_alter_case_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="ton_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
