# Generated by Django 3.2.5 on 2021-08-29 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_alter_task_unique_together"),
        ("cases", "0081_alter_case_ton_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestate",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="workflow.workflow",
            ),
        ),
    ]
