# Generated by Django 3.2.5 on 2021-08-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_alter_task_unique_together"),
        ("cases", "0082_casestate_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestate",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_states",
                to="workflow.workflow",
            ),
        ),
    ]
