# Generated by Django 3.2.5 on 2021-09-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_alter_workflow_workflow_spec"),
        ("cases", "0083_alter_casestate_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestate",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_states",
                to="workflow.workflow",
            ),
        ),
    ]
