# Generated by Django 3.2.7 on 2021-10-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0086_alter_case_is_legacy_camunda"),
    ]

    operations = [
        migrations.RenameField(
            model_name="caseclose",
            old_name="camunda_task_id",
            new_name="case_user_task_id",
        ),
        migrations.RenameField(
            model_name="citizenreport",
            old_name="camunda_task_id",
            new_name="case_user_task_id",
        ),
    ]
