# Generated by Django 3.2.7 on 2021-11-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0087_auto_20211013_1450"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizenreport",
            name="nuisance",
            field=models.BooleanField(default=False),
        ),
    ]
