version: "3.5"

services:
  db:
    image: mdillon/postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=openzaak
      - POSTGRES_USER=openzaak
      - POSTGRES_PASSWORD=openzaak
    networks:
      - open_zaken_network
    volumes:
      - ./docker/postgres.entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - openzaak-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - open_zaken_network
      - zaken_network

  rabbitmq:
    image: rabbitmq:3.7-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - open_zaken_network

  openzaak_local:
    image: openzaak/open-zaak
    networks:
      - open_zaken_network
      - zaken_network
    ports:
      - 80:8000
    env_file:
      - ./open-zaak/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./config:/app/config
      - ./open-zaak/db:/app/src/db

  #
  # OPEN NOTIFICATIES
  #

  open_notificaties_database:
    image: mdillon/postgis
    ports:
      - 5433:5432
    env_file:
      - open-notificaties/.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=open_notificaties
      - POSTGRES_USER=openzaak
      - POSTGRES_PASSWORD=openzaak
    networks:
      - open_zaken_network
    volumes:
      - open-notificaties-data:/var/lib/postgresql/data

  open_notificaties_celery:
    image: openzaak/open-notificaties
    command: /celery_worker.sh
    env_file:
      - open-notificaties/.env
    environment:
      - DJANGO_SETTINGS_MODULE=nrc.conf.docker
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/1
      - RABBITMQ_HOST=rabbitmq
      - PUBLISH_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
      - CELERY_LOGLEVEL=DEBUG
      - SUBPATH=${SUBPATH:-/}
    networks:
      - open_zaken_network
    depends_on:
      - open_notificaties_database
      - redis
      - rabbitmq

  open_notificaties:
    image: openzaak/open-notificaties
    ports:
      - 8888:8000
    env_file:
      - open-notificaties/.env
    networks:
      - open_zaken_network
    depends_on:
      - open_notificaties_database
      - redis

networks:
  zaken_network:
    external: true
  open_zaken_network:
    external: true

volumes:
  openzaak-data:
  open-notificaties-data:
