# Generated by Django 3.2.13 on 2022-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="completed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="top_visit_id",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
