# Generated by Django 3.1.2 on 2020-11-01 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="observations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, size=None
            ),
        ),
    ]
