# Generated by Django 4.2.23 on 2025-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_auto_20220502_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="is_additional",
            field=models.BooleanField(default=False),
        ),
    ]
