# Generated by Django 3.1.2 on 2020-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_auto_20201101_1704"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="can_next_visit_go_ahead",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="can_next_visit_go_ahead_description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="suggest_next_visit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="suggest_next_visit_description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
