# Generated by Django 4.2.23 on 2026-10-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_visit_is_additional"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="case_user_task_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
