# Generated by Django 3.1.3 on 2020-11-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_auto_20201102_0905"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visit",
            options={"ordering": ["-start_time"]},
        ),
    ]
