# Generated by Django 3.1.3 on 2020-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0004_auto_20201106_0416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
