# Generated by Django 3.1.7 on 2021-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0007_auto_20210324_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="can_next_visit_go_ahead",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
