# Generated by Django 3.2.5 on 2021-09-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_alter_workflow_workflow_spec"),
        ("visits", "0008_auto_20210329_1708"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.task",
            ),
        ),
    ]
