# Generated by Django 3.2.7 on 2021-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0009_visit_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="task",
        ),
        migrations.AddField(
            model_name="visit",
            name="case_user_task_id",
            field=models.CharField(default="-1", max_length=255),
        ),
    ]
