# Generated by Django 3.2.7 on 2021-11-16 09:57
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = []
    # operations = [
    #     migrations.CreateModel(
    #         name="Fine",
    #         fields=[
    #             (
    #                 "id",
    #                 models.AutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "identification",
    #                 models.CharField(
    #                     blank=True, max_length=255, null=True, unique=True
    #                 ),
    #             ),
    #             (
    #                 "case",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.CASCADE,
    #                     related_name="fines",
    #                     to="cases.case",
    #                 ),
    #             ),
    #         ],
    #     ),
    # ]
