name: 'Validate BPMN'
on:
  push:
    branches: [ master ]
    paths:
    - 'app/apps/workflow/bpmn_files/**/**/**/*.bpmn'
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js for BPMN Linting
      uses: actions/setup-node@v3.5.0
      with:
        node-version: '12.x'
    - name: Install dependencies for BPMN Linting
      run: npm install -g bpmnlint
    - name: Linting BPMN models
      run: bash bin/validate_bpmn.sh
