# action.yml
name: 'Install, lint, test & build'
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      ###################################################
      # CHECKOUT
      ###################################################
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          path: backend
          repository: amsterdam/zaken-backend

      ###################################################
      # Build
      ###################################################
      - run: docker network create fixxx-looplijsten-backend_looplijsten_backend
        working-directory: backend

      - run: docker-compose build
        working-directory: backend
        
      ###################################################
      # Tests
      ###################################################
      - run: docker-compose run --rm zaak-gateway python manage.py test
        working-directory: backend
        
