# action.yml
name: "Run Integration test"
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      ###################################################
      # CHECKOUT
      ###################################################

      - name: Checkout backend
        uses: actions/checkout@v3

      ###################################################
      # BACKEND
      ###################################################

      - run: docker network create zaken_network
      - run: docker network create top_and_zaak_backend_bridge
      - run: docker-compose -f docker-compose.test.yml up --detach
      - run: sleep 30
      - run: bash bin/setup_credentials.sh
      - run: ./e2e-tests/fix_models.sh

      ###################################################
      # TEST
      ###################################################

      - run: sudo apt-get install python3.9

      # Test version
      - run: python --version

      - run: python3 -m pip install -r requirements.txt
        working-directory: e2e-tests

      - run: API_HOST=http://127.0.0.1:8080/api/v1 python3 -m unittest
        working-directory: e2e-tests

      ###################################################
      # On failure
      ###################################################

      - if: ${{ failure() }}
        name: "ON FAILURE: Which containers were running while failing?"
        run: docker ps -a

      - if: ${{ failure() }}
        name: "ON FAILURE: Backend logs"
        run: docker logs zaken-backend_zaak-gateway_1

      - if: ${{ failure() }}
        name: "ON FAILURE: Database logs"
        run: docker logs zaken-backend_database_1
