# action.yml
name: 'Run E2E test'
on: pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      ###################################################
      # CHECKOUT
      ###################################################
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          path: frontend
          repository: amsterdam/zaken-frontend

      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          path: backend

      ###################################################
      # BACKEND
      ###################################################
      - run: docker network create fixxx-looplijsten-backend_looplijsten_backend
        working-directory: backend

      - run: docker-compose up --build --detach
        working-directory: backend

      ###################################################
      # FRONTEND
      ###################################################
      - run: npm install
        working-directory: frontend

      - run: npm run lint:fix
        working-directory: frontend

      - run: npm run start &>/dev/null &
        working-directory: frontend

      - run: npm run cypress:run
        working-directory: frontend

      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: ./frontend/cypress/videos/

      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: ./frontend/cypress/screenshots/

      ###################################################
      # On failure
      ###################################################

      - if: ${{ failure() }}
        name: "ON FAILURE: Which containers were running while failing?"
        run: docker ps -a

      - if: ${{ failure() }}
        name: "ON FAILURE: Backend logs"
        run: docker logs backend_zaak-gateway_1

      - if: ${{ failure() }}
        name: "ON FAILURE: Database logs"
        run: docker logs backend_database_1
