# action.yml
name: 'Run Integration test'
on: pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      ###################################################
      # CHECKOUT
      ###################################################

      - name: Checkout backend
        uses: actions/checkout@v2

      ###################################################
      # BACKEND
      ###################################################

      - run: docker network create zaken_network
      - run: docker network create top_and_zaak_backend_bridge
      - run: docker-compose -f docker-compose.test.yml build
      - run: docker-compose -f docker-compose.test.yml up --detach
      - run: docker-compose run --rm zaak-gateway python manage.py migrate
      - run: docker-compose run zaak-gateway python manage.py shell -c "from apps.summons.models import SummonType; type = SummonType.objects.get(pk=13); type.camunda_option='sluiting'; type.save(); SummonType.objects.get_or_create(camunda_option='legalisatie-brief', name='Legalisatie-brief', theme_id=1)"
      - run: bash bin/setup_credentials.sh
      - run: sleep 30


      ###################################################
      # TEST
      ###################################################

      - run: sudo apt-get install python3.9

      - run: python3.9 -m pip install -r testing/requirements.txt

      - run: LOGLEVEL=INFO python3.9 -m unittest
        working-directory: testing


      ###################################################
      # On failure
      ###################################################

      - if: ${{ failure() }}
        name: "ON FAILURE: Which containers were running while failing?"
        run: docker ps -a

      - if: ${{ failure() }}
        name: "ON FAILURE: Backend logs"
        run: docker logs zaak-gateway_1

      - if: ${{ failure() }}
        name: "ON FAILURE: Database logs"
        run: docker logs database_1
