# action.yml
name: 'Start frontend'
on: pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      ###################################################
      # CHECKOUT
      ###################################################
      - name: Checkout frontend
        uses: actions/checkout@v3
        with:
          path: frontend
          repository: amsterdam/zaken-frontend

      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          path: backend

      ###################################################
      # BACKEND
      ###################################################
      - run: docker network create zaken_network
        working-directory: backend

      - run: docker network create top_and_zaak_backend_bridge
        working-directory: backend

      - run: docker-compose -f docker-compose.local.yml up -d
        working-directory: backend

      ###################################################
      # FRONTEND
      ###################################################
      - run: npm install
        working-directory: frontend

      - run: npm run lint:fix
        working-directory: frontend

      - run: npm run start &>/dev/null &
        working-directory: frontend

      ###################################################
      # On failure
      ###################################################

      - if: ${{ failure() }}
        name: "ON FAILURE: Which containers were running while failing?"
        run: docker ps -a

      - if: ${{ failure() }}
        name: "ON FAILURE: Backend logs"
        run: docker logs backend_zaak-gateway_1

      - if: ${{ failure() }}
        name: "ON FAILURE: Database logs"
        run: docker logs backend_database_1
